### ISSUE TITLE
IDA 8.4 crashes in FlareVM when running python scripts

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#1017]
### What's the problem?

There was an issue raised from user feedback that IDA 8.4 may sometimes crash when running python scripts.

It was suggested from Igor that upgrading to Python 3.12 may fix this issue and per user feedback, this did seem to work.

@Ana06 We may want to look into making our default Python installation be version 3.12 to avoid this potential issue for other users.

### Steps to Reproduce

Attempt to use python script with IDA Pro 8.4.

### Environment

Environment Agnostic

### Detected by test suite

No

**Comment by Ana06** [comment]
This looks to me like an IDA Pro bug related to the following mentioned in the [release note](https://hex-rays.com/products/ida/news/8_4/):
> BUGFIX: IDAPython: IDAPython would fail to initialize on Python 3.12 release due to missing 'imp' module

Updating to Python Python 3.12 may fix IDA Pro, but may break other tools and libraries. So, I think we should not try to fix this IDA bug in FLARE-VM. I think supporting only the latest IDA version in IDA python is an important IDA Pro bug and I expect IDA to resolve it fast.

**Comment by Ana06** [comment]
The bug has been fixed in IDA Pro v8.4.240527 so I think we can close this issue.
