### ISSUE TITLE
Remove Chrome dependency in cyberchef.vm thank to new changes

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1021]
### Details

I think with the changes in https://github.com/mandiant/VM-Packages/pull/1016 we could now remove  the Chrome dependency in Cyberchef and the code to open it with chrome and set the icon (simplifying the installer code). I think we would keep the current behavior if both cyberchef.vm and googlechrome.vm are installed and remove the chrome dependency would allow to have a different browser as default (and to open cyberchef) if only cyberchef.vm is installed. This would need to add googlechrome.vm explicitly in [flare-vm](https://github.com/mandiant/flare-vm/blob/main/config.xml).

@emtuls what do you think?

**Comment by Ana06** [comment]
`VM-Set-Open-With-Association $exePath ".html"` changes the icon but not the default icon, right? I think this is confusing, we should change the icon of html + default browser or remove the icon association. Let's discuss in https://github.com/mandiant/VM-Packages/issues/822 if we can change the default browser.

**Comment by emtuls** [comment]
I may have a working solution for this. 😊 I still need to test how the new shortcut would work if chrome was not installed, but at least for the chrome case...After using `VM-Set-Open-With-Association $exePath ".html"`, we just need to create the following registry key and then restart `explorer.exe`:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer]
“NoNewAppAlert”=dword:00000001
```

**NOTE**: This does not make `chrome` the default browser still, which also makes the popup asking to make `chrome` the default browser still appear. I can look into seeing if I can bypass that as well, without actually setting the default browser, but it may not be possible.

**Comment by Ana06** [comment]
Because of the changes in https://github.com/mandiant/VM-Packages/pull/1148, we can't remove the dependency
