### ISSUE TITLE
Make x64dbg related packages naming consistent

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1039]
### Details

At the moment we have the following packages related to `x64dbg`:
- [x64dbg.dbgchild.vm](https://github.com/mandiant/VM-Packages/tree/main/packages/x64dbg.dbgchild.vm)
- [x64dbg.ollydumpex.vm](https://github.com/mandiant/VM-Packages/tree/main/packages/x64dbg.ollydumpex.vm)
- [x64dbg.scyllahide.vm](https://github.com/mandiant/VM-Packages/tree/main/packages/x64dbg.scyllahide.vm)
- [x64dbgpy.vm](https://github.com/mandiant/VM-Packages/tree/main/packages/x64dbgpy.vm)

Should we rename them to make them consistent (between them and with the `ida.plugin.` packages)? Proposal:

- `x64dbg.plugin.dbgchild.vm`
- `x64dbg.plugin.ollydumpex.vm`
- `x64dbg.plugin.scyllahide.vm`
- `x64dbg.plugin.x64dbgpy.vm`

@mandiant/flare-vm opinions?

**Comment by thejoelpatrol** [comment]
That suggestion is clear to me, no objection as the author of `x64dbg.dbgchild.vm`
