### ISSUE TITLE
windbg download link is broken

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1040]
### Details

The link we use in the installer and the one in the [_Install the Windows debugger_ page from Microsoft](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/) seem to be broken. The package is failing to install in the daily run because of this issue.

Does anyone know what the issue is or how to best report this to Microsoft? Alternatively, is there any other link to install the tool?

**Comment by naacbin** [comment]
I think, we can use the same link as in [winget](https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/WinDbg/1.2402.24001.0/Microsoft.WinDbg.installer.yaml) :
https://windbg.download.prss.microsoft.com/dbazure/prod/1-2402-24001-0/windbg.msixbundle

**Comment by Ana06** [comment]
@naacbin thanks for sharing the idea! but that link seems to be broken for me too. It is interesting that the daily fails to install windbg only some times. Could it be the microsoft links are broken but not all the time? :thinking:

**Comment by naacbin** [comment]
It seems as yesterday when I send it, it was working...

**Comment by Ana06** [comment]
In the daily run, it only fails sometimes: https://github.com/mandiant/VM-Packages/wiki/Daily-Failures

**Comment by stevemk14ebr** [comment]
You may want to check if this is any better the windbg folks are looking at fixing their CDN

**Comment by Ana06** [comment]
According to [our daily test run](https://github.com/mandiant/VM-Packages/wiki/Daily-Failures), this issue is fixed. Can we close this issue?

**Comment by Ana06** [comment]
Closing as the issue seems to be fixed. :smile:
