### ISSUE TITLE
Fix calls to `VM-Uninstall-With-Uninstaller` which miss category

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1055]
### Details

Ensure all calls to `VM-Uninstall-With-Uninstaller` include the category. Some are missing it, examples:
-  `VM-Uninstall-With-Uninstaller "Nmap*" "EXE" "/S"` in [nmap.vm](packages/nmap.vm/tools/chocolateyuninstall.ps1)
- `VM-Uninstall-With-Uninstaller "IDA Freeware*?8.3" "EXE" "--mode unattended"` in [idafree](https://github.com/mandiant/VM-Packages/blob/caf4585bb3a42992c0fd6f9b6873bbb9dd46443a/packages/idafree.vm/tools/chocolateyuninstall.ps1#L13) (fixed proposed in https://github.com/mandiant/VM-Packages/pull/1053/files#diff-ade493caf784b089b43b49ec10580f9406695fbe7efc7b141c888dd0a6794f65R24

**Comment by naacbin** [comment]
I have tested do to the same fix to `nmap.vm`, but it turned out that the uninstaller `VM-Uninstall-With-Uninstaller` won't work. Nmap uninstaller is located in `C:\Tools\nmap`, but as the function delete all files in `C:\Tools\<toolName>` and then try to use the uninstaller it fail.
