### ISSUE TITLE
Package not pushed to myget after merged PR

### ISSUE THREAD

**Issue by naacbin** [mandiant/VM-Packages#1061]
### What's the problem?

Both PR merge [2145](https://github.com/mandiant/VM-Packages/actions/runs/9257543745/job/25465914763) and [2148](https://github.com/mandiant/VM-Packages/actions/runs/9265433407/job/25487493721) have a CI that has failed, meaning that no packages have been uploaded to MyGet. For the first one it's due to the hash of IDA that was incorrect at the moment of the merge. Even if IDA is now fixed  (#1060) other packages in the PR haven't been pushed. For the second one, it's because `npcap.com` site was and is still down (fyi `nmap.org` is down too),. Once they are back again, a rerun of the job should be enough.

### Steps to Reproduce

N/A

### Environment

N/A

### Detected by test suite

No

**Comment by naacbin** [comment]
I have re-run the CI job for [2148](https://github.com/mandiant/VM-Packages/actions/runs/9265433407/job/25591435872), the packages from #1052 are now available on MyGet. However, for the CI of #1053 ([2145](https://github.com/mandiant/VM-Packages/actions/runs/9257543745/job/25465914763), packages must be uploaded manually to MyGet, as the hash of IDA has changed the CI will always fail. @Ana06

**Comment by Ana06** [comment]
Thanks for letting me know @naacbin! We should push the packages and then ensure that this does not happen again (for example changing the CI to push the packages that do work or/and addressing https://github.com/mandiant/VM-Packages/issues/132). 

If I understand correctly, we need to push all packages in https://github.com/mandiant/VM-Packages/pull/1053. I'll try to do this manually later today. Alternatively editing the packages time in the nuspec version and merging that PR would push them as well.

**Comment by naacbin** [comment]
> If I understand correctly, we need to push all packages in #1053. I'll try to do this manually later today. Alternatively editing the packages time in the nuspec version and merging that PR would push them as well.

Yes, all except IDA.

**Comment by Ana06** [comment]
I am thinking adding a GH action to push all packages would be a good solution, then we can trigger it manually as needed. :thinking:

**Comment by Ana06** [comment]
Sorry for the late reply @naacbin, this is important, but I have had some busy days. 

After taking a closer look to this, I think:
- We should try to avoid updating many packages in the same PR (if the update is not related) as it makes reviewing the changes easier/faster and prevents failures like the one in this issue. In general atomic changes are a good idea. I'll document this.
- We should ensure the CI in PRs run in the same day before merging it (specially if many packages are updated at the same time). I'll document this.
- We should address https://github.com/mandiant/VM-Packages/issues/132 to ensure we notice the issue if it happens again. I am working on it right now.
- We should push the missing packages using a PR where we increase the version to push the packages using the same procedure as usual. I will send 2 PRs for this.

I considered modifying the GH actions to push the packages that succeed even when others in the same PR fail when merging. But this can have unexpected effects if the changes in the packages are related (what is often the case for changes in the same PR). It doesn't happens often (it is the first time that I remember), so I think we can decide how to handle and handle it manually if it happens again.

Does this sound good to you @naacbin @mandiant/vms ?

**Comment by naacbin** [comment]
> Sorry for the late reply @naacbin, this is important, but I have had some busy days.

Same for me no, worries.

> Does this sound good to you @naacbin @mandiant/vms ?
A little bit too late but LGTM !

Thanks for all the recent merge @Ana06
