### ISSUE TITLE
Change the URL of Package ExtremeDumper

### ISSUE THREAD

**Issue by superguo** [mandiant/VM-Packages#1064]
### What's the problem?

ExtremeDumper's official links ([Github Link](https://github.com/wwh1004), [Personal Homepage](https://wwh1004.com/)) and downloadable [URL](https://github.com/wwh1004/ExtremeDumper/releases/latest/download/ExtremeDumper.zip)  are all dead. Please use another link.
Package: packages/extreme_dumper.vm
Suggested alternative link: https://github.com/cunyterg/ExtremeDumper/archive/refs/tags/v4.0.0.1.zip

### Steps to Reproduce

1. Run PowerShell as Administrator
2. Run the following code
`git clone https://github.com/mandiant/flare-vm.git`
`cd flare-vm`
`choco install -y extreme_dumper.vm`

### Environment

- Virtualization software: VMWare Workstation 17 Pro
- VM OS version: 10.0.17763
- VM PowerShell version: 5.1.17763.316
- VM Chocolatey version: 2.2.2
- VM Boxstarter version: 3.0.3

### Detected by test suite

No

**Comment by superguo** [comment]
@Ana06 The developer seems to have moved all projects to [Gitcode](https://gitcode.com/wwh1004) . So the more official and downloadable URL is: 
https://raw.gitcode.com/wwh1004/ExtremeDumper/archive/refs/heads/master.zip

**Comment by Ana06** [comment]
Thanks for the info @superguo! The zip we were using before contained the `.exe`, but I do not see it in the ZIPs you have linked. :thinking:

**Comment by superguo** [comment]
@Ana06 Oh, the previous two links contain only code. After some investigation I found that the project has another [backup](https://gitee.com/keyestore/ExtremeDumper) with release zip file containing two `.exe`s, please give it a try.
https://gitee.com/keyestore/ExtremeDumper/releases/download/v4.0.0.1/ExtremeDumper.zip
