### ISSUE TITLE
scripts/test/test_install.ps1 is broken - $built_pkgs is a list of True and False

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#107]
### What's the problem?

Issue introduced in https://github.com/mandiant/VM-Packages/pull/103. `$built_pkgs` is now a list of True and False and not a list of packages names.

```Powershell
PS VM-Packages > $built_pkgs = Get-ChildItem $built_pkgs_dir | Foreach-Object { ([regex]::match($_.BaseName, '(.*?[.](?:vm)).*').Groups[1].Value) -and $_ -notin $exclude_tests}
FLARE 11/21/2022 1:57:05 PM
PS VM-Packages > $built_pkgs
True
True
True
```

### Steps to Reproduce

See https://github.com/mandiant/VM-Packages/actions/runs/3511009362/jobs/5881380101 or run `scripts/test/test_install.ps1` locally.

### Detected by test suite

As there was no package update in https://github.com/mandiant/VM-Packages/pull/103, the issue was not detected by the CI. But now it fails for every package update. See https://github.com/mandiant/VM-Packages/pull/106.

**Comment by MalwareMechanic** [comment]
Fixed with #109
