### ISSUE TITLE
VS Code Python Extension

### ISSUE THREAD

**Issue by mwilliams31** [mandiant/VM-Packages#1074]
### Details

Include the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) for VS Code. This installs  two extensions: [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) and [Python Debugger](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy). Without the Python Debugger extension (or similar), Python scripts cannot be debugged in VS Code.

Another extension to consider including is [Jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter).

**Comment by Ana06** [comment]
thanks for the issue @mwilliams31! I suggest we implement two additional packages `vscode.python.vm` and `jupyter.python.vm` and add at least the first one to the FLARE-VM default configuration. @mandiant/vms opinions? @mandiant/flare-vm do you think we should add jupyter to the default configuration?

**Comment by day1player** [comment]
there are some existing packages for this it looks like?
https://community.chocolatey.org/packages/vscode-pylance
https://community.chocolatey.org/packages/vscode-python
https://community.chocolatey.org/packages/vscode-jupyter

**Comment by emtuls** [comment]
I don't think it hurts to have the `jupyter` one in the default as well. I know it can be useful in `vscode`, so I imagine it could be for that as well, and that's a tool that many people use when doing Python & Data type work, which FlareVM makes sense for that situation when it comes to Data Analysis on Malware.

**Comment by Ana06** [comment]
@emtuls @emtuls is there something against using the community packages @day1player proposed so that we do not have to maintain the two extra packages? (I have just seen his proposal)

We should add either the community packages or the .vm packages to the flare-vm default configuration.

**Comment by d35ha** [comment]
@Ana06 
I don't see a problem in  using VS marketplace directly, it enables us to have a better version control.
