### ISSUE TITLE
npm package proposal: js-beautify.vm

### ISSUE THREAD

**Issue by mwilliams31** [mandiant/VM-Packages#1075]
### Package Name

js-beautify

### Tool Name

js-beautify

### Package type

NODE

### Version

1.15.1.20240605

### Category

Javascript

### Tool's authors

Einar Lielmanis

### Tool's description

Beautifier for JavaScript

### Why is this tool a good addition?

While CyberChef includes a JavaScript beautifier, it fails on large files. Ideally `js-beautify` could be used in those situations.

**Comment by Ana06** [comment]
We also have [JSTool](https://github.com/sunjw/jstoolnpp) with a _JSFormat_ option in Notepad++:
![image](https://github.com/mandiant/VM-Packages/assets/16052290/053d9ebc-4543-417b-8302-eeda90ac7f59)

@mandiant/flare-vm opinions on adding both tools to the default configuration?

**Comment by emtuls** [comment]
I think it's good to add both. :)
