### ISSUE TITLE
Failed to install ida.plugin.diaphora.vm

### ISSUE THREAD

**Issue by superguo** [mandiant/VM-Packages#1077]
### What's the problem?

I have already installed flare-vm, and I tried to upgrade it by running install.ps1, something went wrong:
(from _log.txt_)

> 2024/06/05 10:37:12 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: ida.plugin.diaphora.vm
> 2024/06/05 10:37:12 [installer.vm] chocolateyinstall.ps1 [+] ERROR : For each failed package, you may attempt a manual install via: choco install -y <package_name>
> 2024/06/05 10:37:12 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed package list saved to: C:\ProgramData\_VM\failed_packages.txt
> 2024/06/05 10:37:12 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Please check the following logs for additional errors:
> 2024/06/05 10:37:12 [installer.vm] chocolateyinstall.ps1 [+] ERROR :    C:\ProgramData\_VM\log.txt (this file)
> 2024/06/05 10:37:12 [installer.vm] chocolateyinstall.ps1 [+] ERROR :    %PROGRAMDATA%\chocolatey\logs\chocolatey.log
> 2024/06/05 10:37:12 [installer.vm] chocolateyinstall.ps1 [+] ERROR :    %LOCALAPPDATA%\Boxstarter\boxstarter.log
> [-] Please check the following logs for any errors:
>         [-] C:\ProgramData\_VM\log.txt
>         [-] %PROGRAMDATA%\chocolatey\logs\chocolatey.log
>         [-] %LOCALAPPDATA%\Boxstarter\boxstarter.log

Then I tried to install **ida.plugin.diaphora.vm** manually after reboot, but it still failed:
(From the console. See **Additional Information** for the screenshot of the console output)

> Chocolatey v2.2.2
> Installing the following packages:
> ida.plugin.diaphora.vm
> By installing, you accept licenses for the packages.
> Progress: Downloading ida.plugin.diaphora.vm 3.2.1... 100%
> 
> ida.plugin.diaphora.vm v3.2.1
> ida.plugin.diaphora.vm package files install completed. Performing other installation steps.
> Using system proxy server '192.168.3.6:7890'.
> File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
> Hashes match.
> Hashes match.
> Extracting C:\Users\IEUser\AppData\Local\ChocoCache\ida.plugin.diaphora.vm\3.2.1\diaphora-3.2.1.zip to C:\Tools\diaphora...
> ERROR: Cannot bind argument to parameter 'Path' because it is an empty string.
> The install of ida.plugin.diaphora.vm was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\ida.plugin.diaphora.vm\tools\chocolateyinstall.ps1'.
>  See log for details.
> 
> Chocolatey installed 0/1 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  \- ida.plugin.diaphora.vm (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ida.plugin.diaphora.vm\tools\chocolateyinstall.ps1'.
>  See log for details.
> FLARE-VM 06/05/2024 19:28:01

### Steps to Reproduce

1. Installed flare-vm, except that some plugin failed to install
  - Posted #1064 for that plugin
  - Waited until it was fixed
2. Tried to upgrade flare-vm by installing it again
3. A window popped up and showed that **ida.plugin.diaphora.vm** will be added
4. Failed (See _log.txt_ in **_What's the problem?_**)
5. Manually rebooted the VM
6. Followed the instruction in the log mentioned above by running 
`choco install -y ida.plugin.diaphora.vm`
7. Still failed (See console output in **_What's the problem?_** for logs)

### Environment

Virtualization software: VMWare Workstation 17 Pro
VM OS version: 10.0.17763
VM PowerShell version: 5.1.17763.316
VM Chocolatey version: 2.2.2
VM Boxstarter version: 3.0.3

### Additional Information

The following screenshot is the output from running `choco install -y ida.plugin.diaphora.vm`

![image](https://github.com/mandiant/VM-Packages/assets/491431/a4212f23-fbd7-4abf-a2a7-288d49dacdd4)

### Detected by test suite

No

**Comment by Ana06** [comment]
Can you please provide the log files `C:\ProgramData\_VM\log.txt` and `C:\ProgramData\chocolatey\logs\chocolatey.log` after installing the failing package?

**Comment by superguo** [comment]
@Ana06 Sure. You don't have to strip the old installation history, because the original log files have been moved to other place before running install.ps1, i.e. these two attached files contain only info about this run.
[log.txt](https://github.com/user-attachments/files/15612748/log.txt)
[chocolatey.log](https://github.com/user-attachments/files/15612751/chocolatey.log)

**Comment by Ana06** [comment]
I see some strange things in the logs:
- I see information saying that `ida.plugin.diaphora.vm` was installed before the error:
  ```
  2024/06/06 02:07:53 [installer.vm] chocolateyinstall.ps1 [+] INFO : 	ida.plugin.diaphora.vm has been installed
  ```
- I see both `ida.diaphora.vm` and `ida.plugin.diaphora.vm` being installed. `ida.plugin.diaphora.vm` is the new version of `ida.diaphora.vm`, so I do not recommend to install both at the same time. @mandiant/flare-vm should we remove `ida.diaphora.vm` from MyGet to avoid confusion?

@superguo please install a fresh install of FLARE (from an empty Windows without any package) and ensure you do not install `ida.diaphora.vm`. Let us know if that resolve the issue.

**Comment by superguo** [comment]
@Ana06 I just uninstalled ida.diaphora.vm and installed ida.plugin.diaphora.vm SUCCESSFULLY. I don't have much time and VPN traffic to do a fresh install, but since no other people or your CI have such a problem, you can close the issue.

**Comment by Ana06** [comment]
Thanks for the follow-up @superguo
