### ISSUE TITLE
Issue with strings

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1086]
### Details

After installing FLARE-VM, the first `strings` in path is not the sysinternals strings, but:
![image](https://github.com/mandiant/VM-Packages/assets/16052290/d8c4c384-d5ea-44a3-b453-41b80ed0e043)

I had expected the sysinternals one. Should we add the sysinternals path at the beginning of PATH in the package? Are there any better solutions? @vm-packages

Also, should we add a shortcut for `strings` in the Tools directory?

**Comment by mr-tz** [comment]
I'd also expect `strings.exe`. I don't think we need a shortcut (there are other strings tools integrated).
