### ISSUE TITLE
Download .NET PDBs with PDBReSym

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1096]
### Details

Download .NET symbols with `PDBReSym.exe cachesyms --sysdir "C:\Windows\Microsoft.NET"` . @mandiant/flare-vm should we add this to the existent [`pdbs.pdbresym.vm`](https://github.com/mandiant/VM-Packages/tree/main/packages/pdbs.pdbresym.vm) package?

**Comment by binjo** [comment]
Sounds good to me :+1:
