### ISSUE TITLE
MAP will eventually break

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#11]
MAP is distributed using the following link for all releases: http://sandsprite.com/idef/map

This makes that an update breaks the package as the hash changes. 😭  We can't ignore the checksum because the URL is using HTTP and Chocolatey complains (with good reasons). 😭😭

**Comment by Ana06** [comment]
@dzzie any chance you can help us? 🥺 The package `map.vm` is going to be used in an update of [FLARE-VM](https://github.com/mandiant/flare-vm). The best option would be to include the `.exe` in the GitHub project or distribute it as a GitHub release. This way the package doesn't break with updates (as the release version or the commit hash would be different) and allows us to run scripts to look for newer versions updating the sha256 hash (using the GitHub API). Alternatively, providing different links for releases (for example http://sandsprite.com/idef/map_0_24) or using HTTPS (https://sandsprite.com/idef/map) would also help us.

If @dzzie is not able to help us, we can install MAP from source (https://github.com/dzzie/MAP).

**Comment by dzzie** [comment]
Hi, I added a github release, or you can just mirror the installer: (my web server does not have https configured)
https://github.com/dzzie/MAP/releases/tag/current

In other news, if you dont have it yet my new vbdec may be of interest for flare vm as well. 
http://sandsprite.com/vbdec/

**Comment by dzzie** [comment]
I did the same for pdfstreamdumper as well: https://github.com/dzzie/pdfstreamdumper/releases/tag/current

**Comment by dzzie** [comment]
and scdbg: https://github.com/dzzie/VS_LIBEMU/releases/tag/current

**Comment by Ana06** [comment]
Thank you for the quick reply @dzzie!!! 💘 

Most projects that use GH releases use the project version and never delete old releases (for example https://github.com/mandiant/capa/releases). Are you planing to do it this way for future releases ? I am asking because I have noticed you have named the release `current`. If the release is never deleted then we can include in the package the sha256 to check it during install. With GH API we can run once in a while (daily/weekly) a script that check the tag of the latest release and sends a PR with updated link and hashes. If you plan to delete/update the releases/tag, the hash will change.

**Comment by dzzie** [comment]
I was just going to keep updating current as updates at this point are just maintenance no real new features.
I can leave the old ones up and just add a new package thats fine too.

**Comment by Ana06** [comment]
> I can leave the old ones up and just add a new package thats fine too.

That would be great, as then we can check the hash 😄 Thanks a lot for the help @dzzie!!!

**Comment by dzzie** [comment]
yup np, if you decide you want to include vbdec I will do the same for it

**Comment by Ana06** [comment]
@dzzie 
> yup np, if you decide you want to include vbdec I will do the same for it

Cool! We plan to allow the community to contribute packages, so of course there will be place for vbdec! We are at the moment getting the project ready to make contributions as easy as possible (documentation, testing, automation, etc.).

**Comment by mr-tz** [comment]
@Ana06 can we close this issue? If so, let's create new issues for @dzzie's currently missing tools.

**Comment by montecarlito** [comment]
![2023-01-04 09_23_59](https://user-images.githubusercontent.com/38365402/210601638-f48ba025-bd61-400e-a935-711b2f0fa16c.png)

Please let me know if this is unrelated and I will submit a new issue with the install script. Everything else installed seamlessly except for Chrome, but that is the easiest manual labor so no complaints overall.

**Comment by dzzie** [comment]
I thought we were using the github link for https support: 
https://github.com/dzzie/MAP/releases/download/current/map_setup.exe

Once in a great while my sandsprite.com server will be unreachable briefly, looks like that was the case here.

**Comment by mr-tz** [comment]
😄 thanks, @dzzie, the current installer still uses the old link

**Comment by mr-tz** [comment]
Thanks @montecarlito, we'll update the link to avoid potential future network issues like what presumably happened for you.
Please let us know if there are other issues.
