### ISSUE TITLE
Download Driver PDBs with PDBReSym

### ISSUE THREAD

**Issue by tarterp** [mandiant/VM-Packages#1117]
### Details

Download symbols with `PDBReSym.exe cachesyms --sysdir "C:\Windows\System32\drivers"`

**Comment by Ana06** [comment]
Thanks for the issues @tarterp, this is a great idea. :smile:  I have just sent a PR to get them added. I have also refactored the code to make it easier to add new ones, in case we need to add any more paths in the future. :wink:
