### ISSUE TITLE
Add magika to Tools directory

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1129]
### Details

Add magika shortcut to the Tools directory. At the moment we are only installing it with Pip.

**Comment by emtuls** [comment]
@Ana06 I believe the function you created [here](https://github.com/mandiant/VM-Packages/blob/6b95e46f12c9e6fd6247bd9fe271203b0008315d/packages/common.vm/tools/vm.common/vm.common.psm1#L1751) creates the shortcut for `magika` still? 

I just tested the latest `choco install magika.vm" and it seems to create a shortcut for it.

**Comment by Ana06** [comment]
it was missing last time I installed FLARE-VM :confused:

**Comment by Ana06** [comment]
I think we can close this issue.
