### ISSUE TITLE
googlechrome.vm fails when Github action image updates to latest chrome

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#1138]
### What's the problem?
As noted in [this](https://github.com/mandiant/VM-Packages/issues/1111#issuecomment-2353439350) comment, when the image that is used by Github Actions updates to use the latest Google Chrome, an error occurs with the `googlechrome.vm` installation because the same version is already installed, thus causing the package to fail to install and any subsequent package that depends on it.

Second, when this package fails to install, it also causes an error for other packages that depend on `googlechrome.vm`, one of those being `cyberchef.vm`, and this raises the error seen in https://github.com/mandiant/VM-Packages/issues/1111. 
When `googlechrome.vm` is not installed, the path to the browser is not in the location we expect, which also causes a failure for finding the icon in the path we are using.
This particular part of the issue will be resolved when we change the icon for CyberChef to be something other than Google Chrome in this PR: https://github.com/mandiant/VM-Packages/pull/1054

See error below for what I mean by `googlechrome.vm` failing to install in the latest run. The image was recently updated to use the latest chrome browser (https://github.com/actions/runner-images/releases/tag/win22%2F20240912.1) and this issue has been noted in other areas as an issue that can occur: https://github.com/yarnpkg/yarn/issues/1647#issuecomment-339732324
![image](https://github.com/user-attachments/assets/d5870053-e8fb-4921-a591-b7f434231163)

### Steps to Reproduce

View our daily logs when Github Action images are updated to latest chrome as noted here: https://github.com/actions/runner-images/releases.

### Environment

Environment Agnostic

Depends on Github Actions Images and when they update to latest chrome.

### Detected by test suite

No

**Comment by Ana06** [comment]
It seems we are not checking valid exit codes (concretely the `1603` in this case) of the installer in the googlechrome package as we do in the [`VM-Install-With-Installer` helper function](https://github.com/mandiant/VM-Packages/blob/6b95e46f12c9e6fd6247bd9fe271203b0008315d/packages/common.vm/tools/vm.common/vm.common.psm1#L679) and in the [donkan.vm package](https://github.com/mandiant/VM-Packages/blob/6b95e46f12c9e6fd6247bd9fe271203b0008315d/packages/dokan.vm/tools/chocolateyinstall.ps1#L11).

@emtuls would you like to add the exit codes check to fix it? :smile:
