### ISSUE TITLE
npm package proposal: asar.vm

### ISSUE THREAD

**Issue by d35ha** [mandiant/VM-Packages#1147]
### Package Name

asar

### Tool Name

asar

### Package type

NODE

### Version

3.2.0.20241002

### Category

Javascript

### Tool's authors

Electron

### Tool's description

Simple extensive tar-like archive format with indexing

### Dependencies

nodejs.vm

### Why is this tool a good addition?

Requested at #1112.

**Comment by Ana06** [comment]
@d35ha you could have edited the existent issue first comment instead of creating a new one (to avoid duplication). You can see the log of the automation here: https://github.com/mandiant/VM-Packages/actions/runs/11141313482/job/30961921733 It is failing because of: 
> ERROR : npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

**Comment by emtuls** [comment]
This is leading to an error when trying to create the package:
https://github.com/mandiant/VM-Packages/actions/runs/11300414747/job/31433219795#step:7:73

```
2024/10/11 23:08:17 [asar.vm] vm.common.psm1 [+] ERROR : npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
At C:\ProgramData\_VM\vm.common\vm.common.psm1:470 char:9
+         npm install -g $toolName --no-update-notifier
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
The upgrade of asar.vm was NOT successful.
```

**Comment by Ana06** [comment]
Closing in favor of https://github.com/mandiant/VM-Packages/issues/1112
