### ISSUE TITLE
Failing and Passing Badges

### ISSUE THREAD

**Issue by MalwareMechanic** [mandiant/VM-Packages#127]
I think having two badges that show the number of "passing" and "failing" packages would be more informative versus a daily badge that simply says "success/fail".

**Comment by mr-tz** [comment]
Agreed, great idea!

**Comment by Ana06** [comment]
It is a great idea, how do you propose to implement it?

**Comment by mr-tz** [comment]
We could update the daily action and maybe `test_install` to set the badges.
