### ISSUE TITLE
Renamed packages are not pushed

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#128]
Some packages (such as `notepadplusplus.vm` renamed in https://github.com/mandiant/VM-Packages/pull/98) haven't been pushed to myget because our action only checks modified nuspec files and not renamed ones if they are not modified. Note that in a package change of name, the version is not modified. We need to:
- Fix action.
- Push packages manually (idea: we could have an action to repush packages so that we don't need to do this manually, but not sure how much we will use it)
- [optional] removed unused/old packages

**Comment by MalwareMechanic** [comment]
- [] All packages deleted
- [] All packages rebuilt and pushed

**Comment by MalwareMechanic** [comment]
Removed `Python2.vm` from VM-Packages

**Comment by mr-tz** [comment]
closed via #129 and above mentioned house-keeping
