### ISSUE TITLE
Package proposal: dependencywalker.vm

### ISSUE THREAD

**Issue by seanthegeek** [mandiant/VM-Packages#155]
### Package Name

dependencywalker

### Tool Name

Dependency Walker

### Package type

ZIP_EXE

### Tool's version number

2.2

### Category

PE

### Tool's authors

Steve P. Miller

### Tool's description

Scans PE files and builds a hierarchical tree diagram of all dependent modules

### Download URL

https://dependencywalker.com/depends22_x64.zip

### Download SHA256 Hash

35db68a613874a2e8c1422eb0ea7861f825fc71717d46dabf1f249ce9634b4f1

### Why is this tool a good addition?

Dependency Walker is a free utility that scans any 32-bit or 64-bit Windows module (exe, dll, ocx, sys, etc.) and builds a hierarchical tree diagram of all dependent modules. For each module found, it lists all the functions that are exported by that module, and which of those functions are actually being called by other modules. Another view displays the minimum set of required files, along with detailed information about each file including a full path to the file, base address, version numbers, machine type, debug information, and more.

**Comment by MalwareMechanic** [comment]
Closing as #160 is complete
