### ISSUE TITLE
Additional Chrome Configuration Packages

### ISSUE THREAD

**Issue by MalwareMechanic** [mandiant/VM-Packages#16]
- config.chrome.defaultbrowser.vm (to make default browser)
- config.chrome.removeshortcut.vm (delete desktop shortcut)
- config.chrome.disableupdates (to disable auto-update for chrome to allow quieter PCAPs)

**Comment by Ana06** [comment]
Tracked in three separate issues to facilitate discussions:

- I think removing the desktop shortcut should be part of the main package as we do this in many other packages as well, but I am not sure how easy is to implement: https://github.com/mandiant/VM-Packages/issues/820
- https://github.com/mandiant/VM-Packages/issues/821
- https://github.com/mandiant/VM-Packages/issues/822

Closing this issue...
