### ISSUE TITLE
Package proposal: procdot.vm

### ISSUE THREAD

**Issue by seanthegeek** [mandiant/VM-Packages#162]
### Package Name

procdot

### Tool Name

ProcDOT

### Package type

ZIP_EXE

### Tool's version number

1.22

### Category

Utilities

### Tool's authors

Christian Wojner

### Tool's description

Creates visual graphs from procmon output

### Download URL

https://procdot.com/download/procdot/binaries/procdot_1_22_57_windows.zip

### Download SHA256 Hash

927cd36dbb4dc0be94afb6021ca7f747dd3f17aad383583bc71aa6e36a762849

### Why is this tool a good addition?

FLARE VM does not have a tool to visualize procmon data. This would be a great addition.

Note: The ZIP has the password "procmon"

**Comment by mr-tz** [comment]
The ZIP password seems to be a stopper at the moment. @MalwareMechanic may have an idea if it's worth handling this.
