### ISSUE TITLE
Package proposal: x64dbg.scyllahide.vm

### ISSUE THREAD

**Issue by seanthegeek** [mandiant/VM-Packages#166]
### Package Name

x64dbg.scyllahide

### Tool Name

x64dbg.scyllahide

### Package type

ZIP_EXE

### Tool's version number

2021-08-23_13-27-50

### Category

Debuggers

### Tool's authors

x64dbg

### Tool's description

Anti-anti-debugging plugin for x64dbg

### Download URL

https://github.com/x64dbg/ScyllaHide/releases/download/snapshot-2021-08-23_13-27-50/ScyllaHide.7z

### Download SHA256 Hash

c51929341ff726d219e670928433a176e114ca9a4c36f416629aef50c98b8817

### Why is this tool a good addition?

Anti-anti-debugging plugin for x64dbg

**Comment by mr-tz** [comment]
Should be installed similarly to `x64dbg.ollydumpex.vm`.
