### ISSUE TITLE
Package proposal: windump.vm

### ISSUE THREAD

**Issue by seanthegeek** [mandiant/VM-Packages#186]
### Package Name

windump

### Tool Name

WinDump

### Package type

ZIP_EXE

### Tool's version number

3.9.5

### Category

Networking

### Tool's authors

Riverbed Technology

### Tool's description

The Windows version of tcpdump

### Download URL

https://www.winpcap.org/windump/install/bin/windump_3_9_5/WinDump.exe

### Download SHA256 Hash

2525041dca2bd37240cca59eb83fa1ec10a4a43716d324dc104dd39db98d358f

### Why is this tool a good addition?

WinDump is the Windows version of tcpdump, the command line network analyzer for UNIX. WinDump is fully compatible with tcpdump and can be used to watch, diagnose and save to disk network traffic according to various complex rules.

**Comment by Ana06** [comment]
Added in https://github.com/mandiant/VM-Packages/pull/949
