### ISSUE TITLE
Package proposal: autopsy.vm

### ISSUE THREAD

**Issue by ghost** [mandiant/VM-Packages#190]
### Package Name

autopsy

### Tool Name

Autopsy

### Package type

SINGLE_EXE

### Tool's version number

4.19.3

### Category

Forensic

### Tool's authors

Brian Carrier

### Tool's description

Autopsy® is a digital forensics platform and graphical interface to The Sleuth Kit® and other digital forensics tools. It is used by law enforcement, military, and corporate examiners to investigate what happened on a computer. You can even use it to recover photos from your camera's memory card.

### Download URL

https://github.com/sleuthkit/autopsy/releases/download/autopsy-4.19.3/autopsy-4.19.3-64bit.msi

### Download SHA256 Hash

c61beb6ad0ccb6182c9af376fd74b12387f6bfac515bada249f8c9ca96f9cb72

### Why is this tool a good addition?

Autopsy is an easy to use, Digital Forensics GUI-based program that allows you to efficiently analyze hard drives and smart phones. It has a plug-in architecture that allows you to find add-on modules or develop custom modules in Java or Python.

**Comment by emtuls** [comment]
Completed: https://github.com/mandiant/VM-Packages/pull/782
