### ISSUE TITLE
Package proposal: nmap.vm

### ISSUE THREAD

**Issue by HuskyHacks** [mandiant/VM-Packages#195]
### Package Name

nmap

### Tool Name

Nmap/Ncat

### Package type

SINGLE_EXE

### Tool's version number

7.93

### Category

Utilities

### Tool's authors

Nmap.org

### Tool's description

Port scanning utility & nc replacement with extended features

### Download URL

https://nmap.org/dist/nmap-7.93-setup.exe

### Download SHA256 Hash

F1160A33FB79C764CDC4C023FA700054AE2945ED91880E37348A17C010CA716F

### Why is this tool a good addition?

Nmap & ncat for port scanning and facilitating network connections for open ports. Accept no substitute!

**Comment by HuskyHacks** [comment]
Note: the official Nmap installer also installs things like ncat and nping. I recommend running the installer with default settings to install the adjacent tools in the package, which are also good for the FLARE-VM use case.

**Comment by mr-tz** [comment]
While not a classical malware analysis tool, this may help with the #193 (because I think Nmap installs Npcap).

**Comment by MalwareMechanic** [comment]
I'll create a custom package for this, the community package for nmap appears to be outdated
