### ISSUE TITLE
Allow to have a different default console

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#2]
We are currently opening console applications using cmd.
```
$executableCmd  = Join-Path ${Env:WinDir} "system32\cmd.exe"
```
I think it would be nice to use a environment variable to allow to change the default console.

**Comment by Ana06** [comment]
Same for the default browser. 🤔

**Comment by MalwareMechanic** [comment]
> Same for the default browser. 🤔

Regarding my comment in https://github.com/mandiant/VM-Packages/pull/15#issuecomment-998445610, I was meaning to say we could have additional configuration packages to allow users to further configure Chrome. For instance, if they wanted the default browser to be Chrome then they could include that package. I think for Win10 you have to manually set your default browser anyway?

**Comment by MalwareMechanic** [comment]
I realized the other tricky part is properly handling paths with spaces correctly. We have this down well for `cmd.exe`, we'd need to figure out for `powershell.exe` and `cmder.exe` the proper way to handle that.

Then we should probably create a function in `vm.common.psm1` to have a big switch statement to handle the bulk logic of:

```
$executableCmd  = Join-Path ${Env:WinDir} "system32\cmd.exe"
$executableDir  = Join-Path ${Env:UserProfile} "Desktop"
$executableArgs = "/K `"cd `"$executableDir`" && `"$executablePath`" --help`""
Install-ChocolateyShortcut -shortcutFilePath $shortcut -targetPath $executableCmd -Arguments $executableArgs -WorkingDirectory $executableDir -IconLocation $executablePath
```

so the users can simply pass in the parameters and not have to worry about handling paths with spaces for each console type.

**Comment by Ana06** [comment]
Closing in favor of https://github.com/mandiant/VM-Packages/issues/971
