### ISSUE TITLE
Should we test all packages?

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#20]
Currently in PR we only test modified packages to reduce the testing time. However, there are cases were a package can break if another package is modified. For example if we modify a function in common, we could break all packages that use that function, that are not tested if they are not modified.

Different approaches to handle this better:
- **Test in all PR all packages.** This take some time, but ensure everything works.
- **Test all packages only in PRs that modify common.** For most PR the testing time is still small, but we ensure that modifying common doesn't break any other package. This only solve the problem for common, but not other dependencies
- **Test only modified packages (current)**. Prioritize small testing time. If something breaks we will realize in the daily run.

@vm-packages  opinions?

**Comment by Ana06** [comment]
In addition, if a package requires a dependency that hasn't been modify, the test suite fails:
![Screenshot 2022-01-13 at 18 58 42](https://user-images.githubusercontent.com/16052290/149384049-805db0f4-df28-4089-aa17-460b00d7d15f.png)

So we need to at least test the dependencies. Ideas how to do this?

**Comment by mr-tz** [comment]
This happened for the `notepadplusplus` package rename and our daily run did not alert us. Is that a separate issue though?

For the general case here I think testing all packages is too much. Can we just test all packages by dependency (based on id/name)?

**Comment by MalwareMechanic** [comment]
I vote for the third option:
> Test only modified packages (current). Prioritize small testing time. If something breaks we will realize in the daily run.

**Comment by mr-tz** [comment]
Agreed, let's close this and reopen, if needed later.
