### ISSUE TITLE
Add pdfstreamdumper

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#213]
I did the same for pdfstreamdumper as well: https://github.com/dzzie/pdfstreamdumper/releases/tag/current

_Originally posted by @dzzie in https://github.com/mandiant/VM-Packages/issues/11#issuecomment-998248647_

**Comment by dzzie** [comment]
Sure I have uploaded a copy with static hash here:

http://sandsprite.com/flare_vm/PDFStreamDumper_Setup_C26068186F63DCCE9CC57502BE742C728110EAB07570C319A0D7D10587A6E22D.exe

Thanks
