### ISSUE TITLE
Package proposal: windows-terminal.vm

### ISSUE THREAD

**Issue by HuskyHacks** [mandiant/VM-Packages#219]
### Package Name

windows-terminal

### Tool Name

Windows Terminal 

### Package type

OTHER/UNKNOWN

### Tool's version number

v1.15.3465.0

### Category

Utilities

### Tool's authors

Microsoft

### Tool's description

The Windows Terminal is a multi-use command prompt terminal window that allows splitting, resizing, and tabbed windows.

### Download URL

https://github.com/microsoft/terminal/releases/download/v1.15.3465.0/Microsoft.WindowsTerminal_Win10_1.15.3465.0_8wekyb3d8bbwe.msixbundle

### Download SHA256 Hash

CAFEF84E6C40260C30F9424193736C24337B93F1413008E47964E957EC1361A3

### Why is this tool a good addition?

Windows Terminal is a huge QOL upgrade over the standard command prompt/PowerShell terminals. It can also integrate with WSL. It also supports themes so you can run your terminal in style with, say, the [Dracula](https://draculatheme.com/windows-terminal) theme.

This would be a great package to give analysts the option to use the Terminal in addition with or in place of cmder.

**Comment by HuskyHacks** [comment]
# Installation steps
Windows Terminal can be installed from an AppX Package.
1. Download the msix bundle from the provided link.
2. In a PowerShell admin window, run: `Add-AppxPackage [C:\path\to\downloaded\msixbundle.msix]`

**Comment by mr-tz** [comment]
Can we create a metapackage for the existing package https://community.chocolatey.org/packages/microsoft-windows-terminal/?

**Comment by HuskyHacks** [comment]
The choco package looks like a better option. I do see some comments about similar issues with the VCLib package so it looks like  that will have to be installed as well.

It's also worth noting that Windows Terminal installs great on Windows 10 and Server 2022, but does not install on Server 2019.

**Comment by Ana06** [comment]
@HuskyHacks we are using Windows Server 2019 in our CI for testing. So if the tool does not install in Windows Server 2019, we can't add it to VM-Packages. I suggest to use the community package as there is no need for a link in the tools folder.
