### ISSUE TITLE
Update dnspyex to Include GUI and 32-bit Version

### ISSUE THREAD

**Issue by MalwareMechanic** [mandiant/VM-Packages#220]
Currently the `dnspyex` package only links the console version. Let's add the shortcut for the GUI as well

https://github.com/mandiant/VM-Packages/blob/6ea288dcb97b8f4fd2556971c7581b8622606c8c/packages/dnspyex.vm/tools/chocolateyinstall.ps1#L7

Also, after looking at https://community.chocolatey.org/packages/dnspyex#files we may need to write our own package versus using a metapackage. Seems they're unzipping using:

``` PowerShell
$packageArgs = @{
  packageName    = $env:ChocolateyPackageName
  fileFullPath   = Get-Item $toolsDir\*-win32.zip
  fileFullPath64 = Get-Item $toolsDir\*-win64.zip
  destination    = $toolsDir
}
Get-ChocolateyUnzip @packageArgs
```

The function [Get-ChocolateyUnzip](https://github.com/chocolatey/choco/blob/38b5e5ce3b083acf591f988243e9d8e8ccbfb832/src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1) function appears to select the `fileFullPath` based on the system architecture. So the 32-bit version may never get unzipped as expected.

**Comment by Ana06** [comment]
I fixed this in https://github.com/mandiant/VM-Packages/pull/413
