### ISSUE TITLE
sysinternals.vm fails due to checksum mismatch (new sysinternals release)

### ISSUE THREAD

**Issue by saladpanda** [mandiant/VM-Packages#222]
### What's the problem?

sysinternals.vm fails due to checksum mismatch.
It is pinned to sysinternals 2022.11.28 but 2023.1.25 was released yesterday.
Since sysinternals does not provide old versions and `choco install sysinternals` always downloads the latest zip no matter the pinned version, this leads to a checksum mismatch.

### Steps to Reproduce

choco install sysinternals.vm

### Environment

See:
https://github.com/mandiant/VM-Packages/actions/runs/4021269899/jobs/6909993479#step:3:2031

### Detected by test suite

Yes

**Comment by mr-tz** [comment]
Thanks,  #221 closes this issue.
