### ISSUE TITLE
Add .NET tools

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#247]

**Comment by mike-hunhoff** [comment]
@Ana06 the version I was referring to is [de4dot-cex](https://github.com/ViRb3/de4dot-cex) (also archived) which is a de4dot fork that adds additional support for ConfuserEx-protected files. I'm not sure what changes outside of then additional ConfuserEx support may have been made so it might be good to include packages for both de4dot and de4dot-cex?

Other .NET tools:
- [GarbageMan](https://github.com/WithSecureLabs/GarbageMan/) (w/ optional [psnotify](https://github.com/WithSecureLabs/GarbageMan/tree/master/psnotify))
- [DotDumper](https://github.com/advanced-threat-research/DotDumper)
- [CodeTrack](https://www.getcodetrack.com/)
- [ILSpy](https://github.com/icsharpcode/ILSpy)
- [dnfile](https://github.com/malwarefrank/dnfile)
- [Python.NET](https://github.com/pythonnet/pythonnet)
- [dncil](https://github.com/mandiant/dncil)
- [dnlib](https://github.com/0xd4d/dnlib)

**Comment by Ana06** [comment]
Thanks @mike-hunhoff

**Comment by Ana06** [comment]
@mike-hunhoff 
> [GarbageMan](https://github.com/WithSecureLabs/GarbageMan/) (w/ optional [psnotify](https://github.com/WithSecureLabs/GarbageMan/tree/master/psnotify))

Do we just need to install psnotify or is there something else that should be configured in GarbageMan to use it? 🤔

**Comment by Ana06** [comment]
Creating a list to track progress here, please update it as progress is made:

- [ ] [de4dot](https://github.com/de4dot/de4dot)
- [x] [de4dot-cex](https://github.com/ViRb3/de4dot-cex) https://github.com/mandiant/VM-Packages/pull/346
- [ ] [GarbageMan](https://github.com/WithSecureLabs/GarbageMan/) (w/ optional [psnotify](https://github.com/WithSecureLabs/GarbageMan/tree/master/psnotify))
- [ ] [DotDumper](https://github.com/advanced-threat-research/DotDumper)
- [ ] [CodeTrack](https://www.getcodetrack.com/)
- [x] [ILSpy](https://github.com/icsharpcode/ILSpy) https://github.com/mandiant/VM-Packages/pull/348
- [ ] [dnfile](https://github.com/malwarefrank/dnfile)
- [ ] [Python.NET](https://github.com/pythonnet/pythonnet)
- [ ] [dncil](https://github.com/mandiant/dncil)
- [ ] [dnlib](https://github.com/0xd4d/dnlib)

**Comment by Ana06** [comment]
@emtuls is #347 in this list (provides or is needed by one of them) or is it another tool you thought it is useful? 🤔

**Comment by emtuls** [comment]
> @emtuls is #347 in this list (provides or is needed by one of them) or is it another tool you thought it is useful? 🤔

That one is not in the list, but is a very useful tool that I've used many times! Also seems to be maintained at the moment.
