### ISSUE TITLE
Error VM-Install-From-Zip on update

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#259]
### What's the problem?

See https://github.com/mandiant/VM-Packages/actions/runs/4312034141/jobs/7522128870#step:4:74

Issue seems to be here?
https://github.com/mandiant/VM-Packages/blob/dd5fd0c73f56a81305c862a34911d07c0462f410/packages/common.vm/tools/vm.common/vm.common.psm1#L329-L331

### Steps to Reproduce

s.a.

### Environment

CI

### Detected by test suite

Yes

**Comment by MalwareMechanic** [comment]
Not a bug 😄 The packages that failed were using the `$innerFolder` flag when it was no longer necessary in updated releases (the folder structure changed in those new releases). I removed the flags in this PR and it passed CI, see: https://github.com/mandiant/VM-Packages/pull/246/commits/56f7725375f7e58cad569851814c83135adb8666#diff-b1d366fe8fdd0d4113827695ebd39c6b4f6b468595b955b0403b820b3eb9f1f6R13
