### ISSUE TITLE
Automatically update GH packages

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#26]
Add a GH action that automatically updates packages with are downloaded from GH URL (such as GitHub releases) and sends a PRs. If the test suite passes, we can just merge it. A relatively easy way to get the last version of many of our tool.

**Comment by mr-tz** [comment]
Doe the same for meta package dependencies - like dependabot.

**Comment by Ana06** [comment]
Open an issue for metapackages as they can be implemented independently.

**Comment by Ana06** [comment]
This is then done.
