### ISSUE TITLE
Lint category

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#270]
The categories are fixed and there is no Email category. See discussion in https://github.com/mandiant/VM-Packages/issues/38

@mr-tz should we add a category check to the linter?

_Originally posted by @Ana06 in https://github.com/mandiant/VM-Packages/pull/253#discussion_r1140315223_

**Comment by Ana06** [comment]
We should also find a way to only have categories in one place 👍

**Comment by Ana06** [comment]
I can move the categories to a file and use this file in the linter and the script to generate more packages. But I am not sure how to avoid the duplication with the issue templates. Any ideas @mr-tz ?

**Comment by mr-tz** [comment]
Not really, we should document where the categories need to be updated. I hope it's less of a problem since we don't plan to change them often.
