### ISSUE TITLE
Things to improve/add in the documentation

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#28]
- [x] Intro about chocolatey (packages structure, important details for us)
- [x] Document [create_package_template.py](https://github.com/mandiant/VM-Packages/blob/main/scripts/utils/create_package_template.py) in the [Quick Start](https://github.com/mandiant/VM-Packages/wiki/Contributing)
- [x] Document requirements for local testing (same as to install FLARE-VM)

**Comment by mr-tz** [comment]
See https://github.com/mandiant/VM-Packages/wiki/Chocolatey and https://github.com/mandiant/VM-Packages/wiki/Testing and Wiki in general.
