### ISSUE TITLE
Update IDAFree

### ISSUE THREAD

**Issue by naacbin** [mandiant/VM-Packages#281]
### What's the problem?

Hi,

It isn't really a bug but I haven't other choice to create this issue. Is it possible to update IDAFree to 8.2 ?

Thanks.

### Steps to Reproduce

N/A

### Environment

N/A

### Detected by test suite

I don't know

**Comment by emtuls** [comment]
Updated to v8.3 here: https://github.com/mandiant/VM-Packages/pull/664
