### ISSUE TITLE
Python3.10 cant install packages.

### ISSUE THREAD

**Issue by Minecradt** [mandiant/VM-Packages#285]
### What's the problem?

I run pip install pynput I expect:   ** Using cached pynput-1.7.6-py2.py3-none-any.whl (89 kB)
Requirement already satisfied: six in c:\users\%username%\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pynput) (1.16.0)
Installing collected packages: pynput
Successfully installed pynput-1.7.6**

but I get:
** Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\pip.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\pip\_internal\cli\main.py", line 68, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "C:\Python310\lib\site-packages\pip\_internal\commands\__init__.py", line 94, in create_command
    module = importlib.import_module(module_path)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python310\lib\site-packages\pip\_internal\commands\install.py", line 14, in <module>
    from pip._internal.cli.req_command import (
  File "C:\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 21, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "C:\Python310\lib\site-packages\pip\_internal\index\package_finder.py", line 32, in <module>
    from pip._internal.req import InstallRequirement
  File "C:\Python310\lib\site-packages\pip\_internal\req\__init__.py", line 7, in <module>
    from .req_file import parse_requirements
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
ValueError: bad marshal data (unknown type code)**

### Steps to Reproduce

1. open command prompt
2. run command pip install pynput

### Environment

VM OS version and Service Pack
-----

Version                 : 10.0.19044
BuildNumber             : 19044
OSArchitecture          : 64-bit
ServicePackMajorVersion : 0
Caption                 : Microsoft Windows 10 Enterprise

VM OS RAM (MB)
-----
2048

VM OS HDD Space / Usage
-----

DeviceID DriveType ProviderName VolumeName Size        FreeSpace
-------- --------- ------------ ---------- ----        ---------
A:       2
C:       3                                 40456155136 6396841984
D:       5

VM AV Details
-----
AntiVirusProduct classname does not exist...

VM PowerShell Version
-----
5.1.19041.1237

VM CLR Version
-----
4.0.30319.42000

VM Chocolatey Version
-----
1.3.1

VM Boxstarter Version
-----

Boxstarter|3.0.0
Boxstarter.Bootstrapper|3.0.0
Boxstarter.Chocolatey|3.0.0
Boxstarter.Common|3.0.0
Boxstarter.HyperV|3.0.0
Boxstarter.WinConfig|3.0.0

VM Installed Packages
-----
010editor.vm|12.0.1
7zip-15-05.vm|15.05
apimonitor|2.13.0.20210213
apimonitor.vm|2.13.0.20220224
apktool|2.7.0
apktool.vm|2.7.0
autohotkey|1.1.36.02
autohotkey.install|1.1.36.02
Boxstarter|3.0.0
Boxstarter.Bootstrapper|3.0.0
Boxstarter.Chocolatey|3.0.0
Boxstarter.Common|3.0.0
Boxstarter.HyperV|3.0.0
Boxstarter.WinConfig|3.0.0
bytecodeviewer.vm|2.11.2
capa.vm|5.0.0
chocolatey|1.3.1
chocolatey-compatibility.extension|1.0.0
chocolatey-core.extension|1.4.0
chocolatey-dotnetfx.extension|1.0.1
chocolatey-visualstudio.extension|1.10.2
chocolatey-windowsupdate.extension|1.0.5
Cmder|1.3.20
cmder.vm|1.3.20.20221201
common.vm|0.0.0.20221220
cyberchef.vm|10.0.0
Cygwin|3.4.6
Error deserializing response of type chocolatey.infrastructure.app.domain.PackageFiles:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
This is try 1/3. Retrying after 400 milliseconds.
 Error converted to warning:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
Error deserializing response of type chocolatey.infrastructure.app.domain.PackageFiles:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
This is try 2/3. Retrying after 600 milliseconds.
 Error converted to warning:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
Error deserializing response of type chocolatey.infrastructure.app.domain.PackageFiles:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
Maximum tries of 3 reached. Throwing error.
cygwin.vm|3.4.6
dnspyex|6.3.0
dnspyex.vm|6.3.0
dotnetfx|4.8.0.20220524
explorersuite.vm|0.0.0.20221115
fakenet-ng.vm|1.4.11.20221115
fiddler|5.0.20211.51073
fiddlerclassic.vm|5.0.20211.20221209
file.vm|0.0.0.20170108
flarevm.installer.vm|0.0.0.20221201
ghidra|10.2.3
ghidra.vm|10.2.3.20230322
hashmyfiles.vm|0.0.0.20220113
hxd|2.5.0.0
hxd.vm|2.5.0
idafree.vm|7.6
javaruntime|8.0.231
jre8|8.0.361
KB2919355|1.0.20160915
KB2919442|1.0.20160915
KB2999226|1.0.20181019
KB3033929|1.0.5
KB3035131|1.0.3
libraries.python2.vm|0.0.0.20221203
libraries.python3.vm|0.0.0.20230315
map.vm|12.20.21
notepadplusplus|8.5.1
notepadplusplus.install|8.5.1
notepadplusplus.vm|8.5.1
notepadpp.plugin.compare.vm|2.0.1.20211225
npcap.vm|1.72
ollydbg.ollydumpex.vm|1.80
ollydbg.vm|1.10.0.20220908
ollydbg2.ollydumpex.vm|1.80
ollydbg2.vm|2.01
openjdk|20.0.0
openjdk11|11.0.16.20220913
peid.vm|0.95.0.20221115
processdump.vm|2.1.1.20220908
python2|2.7.18
python3|3.10.0
python3.vm|3.10.0.20230314
regshot.vm|1.9.1
rundotnetdll.vm|2.2
sysinternals|2023.4.4
sysinternals.vm|2023.4.4
Error deserializing response of type chocolatey.infrastructure.app.domain.PackageFiles:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
This is try 1/3. Retrying after 400 milliseconds.
 Error converted to warning:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
Error deserializing response of type chocolatey.infrastructure.app.domain.PackageFiles:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
This is try 2/3. Retrying after 600 milliseconds.
 Error converted to warning:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
Error deserializing response of type chocolatey.infrastructure.app.domain.PackageFiles:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
Maximum tries of 3 reached. Throwing error.
telnet.vm|0.0.0.20230317
Temurin11|11.0.18.1000
uniextract2.vm|2.0.0.20220113
vcbuildtools.vm|0.0.0.20230322
vcredist140|14.34.31938
vcredist2010|10.0.40219.32503
vcredist2015|14.0.24215.20170201
visualstudio2017buildtools|15.9.53.0
visualstudio2017-workload-vctools|1.3.3
visualstudio-installer|2.0.3
wireshark|4.0.4
wireshark.vm|4.0.4
x64dbg.ollydumpex.vm|1.80
x64dbg.vm|2021.05.08
x64dbgpy.vm|1.0.56.20211021

### Detected by test suite

No

**Comment by mr-tz** [comment]
Does this only occur in your FLARE VM install? Maybe https://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data can help?

**Comment by Ana06** [comment]
@Minecradt does @mr-tz solution fixes your issue? FLARE-VM installs libraries.python3.vm that uses python 9, so I think this error is not related to out packages. I am going to close this issue, please reopen it if you have more information.
