### ISSUE TITLE
Use username with spaces in CI

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#29]
In the past we had bugs related to usernames with spaces. If possible use a username with spaces in GH actions.

**Comment by mr-tz** [comment]
Added recommendation on usernames to flare-vm setup/install section (currently open PR).

**Comment by MalwareMechanic** [comment]
I like the recommendation in the README.md. I'm good with tabling this now since it's a recommendation.

**Comment by MalwareMechanic** [comment]
Added recommendation in README.md, closing for now
