### ISSUE TITLE
Updating the success/failure badges noisy in the commit history

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#290]
The number of success/failure packages tend to vary a lot in the last runs, generating a lot of `Update daily success/failure badges` commits. I find this commit noisy. I think it would be better to have a central log of failing packages instead that is easier to read and does not appear in the commit history.

Idea:
- Have a file with the number of success/failure packages every day in the wiki. This will create a commit in the wiki (but I think it is better than in the code and it provides an overview of the failures)

Other ideas?

**Comment by mr-tz** [comment]
Agreed, we could also append it to a (CSV) file. I don't think the labels turned out to be as useful as anticipated.

**Comment by Ana06** [comment]
Can we have a CSV file in the wiki? Because I would like to move outside of this repository the log to avoid creating daily commits.

**Comment by mr-tz** [comment]
Ah, right. Append to Wiki page should be possible.

**Comment by Ana06** [comment]
Fixed in https://github.com/mandiant/VM-Packages/pull/300, log is in https://github.com/mandiant/VM-Packages/wiki/Daily-Failures
