### ISSUE TITLE
Re-add Chrome as a dependency for CyberChef

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#296]
The Google Chrome community package uses a link that doesn't include the version and breaks every time a new version of Chrome is released (which happens often). This break the cyberchef package until the community package is updated and we update the dependency (which happens automatically once a week). We could remove this dependency as use the default browser instead.

**Comment by mr-tz** [comment]
I think that's fair as Chrome is not required to install the CyberChef page. We could add a meta package that installs Chrome (best effort).

**Comment by Jbha** [comment]
Hello,

I'm trying to install flare-vm but is stops running because of the google issue. Can some help me with this ? 

Kind regards
Joachim

**Comment by mr-tz** [comment]
CyberChef/Chrome have been updated.

**Comment by Ana06** [comment]
But I think it is still a valid question if the dependency should be required. We could install cyberchef without Chrome. Taking into account that chome fails quite often (because of version updates), I think we should consider making the installation of Chrome best effort (at least as an option).

**Comment by Ana06** [comment]
It doesn't look like people miss Chrome.

**Comment by Ana06** [comment]
Maybe https://github.com/mandiant/VM-Packages/issues/469 could also fix this.

**Comment by Ana06** [comment]
## Status
Readd Chrome as dependency for CyberChef after fixing Chrome with https://github.com/mandiant/VM-Packages/issues/469

**Comment by Ana06** [comment]
Addressed in https://github.com/mandiant/VM-Packages/pull/844
