### ISSUE TITLE
why do we need a python3 package?

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#301]
python3.vm is just installing the community package, there is no even chocolateyinstall.ps1 file. Why do we need this package?

**Comment by mr-tz** [comment]
Good question :) In another thread we talked about adding other default packages. If we come up with a good solution to also install existing choco packages we could save a lot of overhead duplicating them.

**Comment by Ana06** [comment]
There is already a way to do this, adding them to the/your [config file](https://github.com/mandiant/flare-vm/blob/main/config.xml). In the case of python3, it would be a dependency for `libraries.python3.vm`. Or am I missing something?

**Comment by Ana06** [comment]
I understand we can get ride of this, is that right @mr-tz ?

**Comment by mr-tz** [comment]
Yeah, do we have to add it to the profile or something so Py3 gets installed then?

**Comment by Ana06** [comment]
I think python 3.9 comes installed by default in Windows 10, but the package libraries.python3.vm installs it anyway.
