### ISSUE TITLE
Package proposal: nasm.vm

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#307]
### Package Name

nasm

### Tool Name

nasm

### Package type

INSTALLER_EXE

### Tool's version number

2.16.01

### Tool's authors

NASM Authors

### Tool's description

Netwide Assembler

### Download URL

https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-installer-x64.exe

### Download SHA256 Hash

08dba33ce8425b92461ef4161f24379bd55b08b18e11cf2b75ebb2422f4b0248

### Why is this tool a good addition?

We need this package for FLARE-EDU to use it with Visual Studio. Related to https://github.com/mandiant/VM-Packages/issues/306

**Comment by Ana06** [comment]
We can probably add a new `INSTALLER_EXE` package type to create packages like this automatically. See another similar package: [vbdec.vm](https://github.com/mandiant/VM-Packages/blob/e5e526c9738e8535bda49063496d87dfc5abc647/packages/vbdec.vm/tools/chocolateyinstall.ps1).

**Comment by Ana06** [comment]
We probably don't want to install this in any category.

**Comment by Ana06** [comment]
As we don't need to install this into a category maybe it is enough to use directly the community package [nasm](https://community.chocolatey.org/packages/nasm). Should we add this in FLARE-VM or as a dependency of Visual Studio?

**Comment by mr-tz** [comment]
I think a separate package would make sense, but if it's easiest as a dependency that's good too.
