### ISSUE TITLE
Idea: make libraries.python3.vm fail in testing in modules fail

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#336]
libraries.python3.vm is (I think) the only package for which we use `$ErrorActionPreference = 'Continue'` to try to install as many modules as possible. This means that in testing we are missing any error when installing python libraries. Should we make this fail during testing?

**Comment by mr-tz** [comment]
if it's easy to do, sure, but I think it's also fine as is

**Comment by Ana06** [comment]
This is already the case 🙈 https://github.com/mandiant/VM-Packages/blob/main/packages/libraries.python3.vm/tools/chocolateyinstall.ps1#L40
