### ISSUE TITLE
Default python version

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#337]
We are installing python3 libraries using python 3.9 in libraries.python3.vm. But some other packages require a different python version. For example:
- stringsifter.vm needs Python 3.8: https://github.com/mandiant/stringsifter/issues/31
- adconnectdump.vm needs Python 2

So if we install libraries.python3.vm and then adconnectdump.vm the path will looks something like this:
```
C:\Python27\;C:\Python27\Scripts;C:\Python39\Scripts\;C:\Python39\;C:\ProgramData\Boxstarter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\010 Editor;C:\Users\flare\AppData\Local\Microsoft\WindowsApps;
```

Which means that `python` will use `python2` by default. This tools don't really need the python version added to the path, just the tool executable.

How should we handle this? 

We could add a function in common that could reorder the path to ensure python3.9 is on top and call it from these kind of package. What do you think? Other ideas?

**Comment by Ana06** [comment]
I am trying to update stringsifter to Python 3.9.

For the packages that don't run in Python 3.9, we could display a warning message in the package and let the user handle this (by installing packages in the right order of fixing the path manually).

**Comment by mr-tz** [comment]
Sounds good to me

**Comment by Ana06** [comment]
Partially resolved. Rest tracked in https://github.com/mandiant/VM-Packages/issues/673

**Comment by Ana06** [comment]
I think we have no documentation about Python2, but I think we have no tools using Python2 anymore. Having several python version has shown to be an issue and I think we should continue to have a single default python version. @mandiant/vms what is a good place to document this? 🤔
