### ISSUE TITLE
ILSpy is missing dependencies (.NET tool)

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#368]
ILSpy introduced in https://github.com/mandiant/VM-Packages/pull/348 is missing dependencies and doesn't run. The CI only tests if the packages install. Manual testing is needed to ensure the tool work as expected.

![Screenshot 2023-05-26 at 11 18 14](https://github.com/mandiant/VM-Packages/assets/16052290/4b36b5b5-fb7a-49f9-aa76-df9562e38bd7)

**Comment by emtuls** [comment]
I believe this has been fixed, according to my testing.

**Comment by Ana06** [comment]
The latest dependency version (which was updated via our CI) includes [dotnet-6.0-desktopruntime](https://community.chocolatey.org/packages/dotnet-6.0-desktopruntime) as dependency.
