### ISSUE TITLE
`notepadplusplus.vm` fails sometimes with `access is denied`

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#41]
It seems that installing `notepadplusplus.vm` fails sometimes with `access is denied`: https://github.com/mandiant/VM-Packages/runs/6088818786?check_suite_focus=true It successes in some daily runs and fails in others.

I forgot to add the upload of logs to the daily in https://github.com/mandiant/VM-Packages/pull/22, I'll send a PR in a moment that may help us figuring out what the problem is.

**Comment by mr-tz** [comment]
I don't think this happened for a longer time. Can we close this?
