### ISSUE TITLE
dnspyex.vm: community package does not install both 64 and 32 versions

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#412]
@emtuls
> I believe that in order to properly debug a 32 bit .NET file, you need to use the 32 bit version, and for a 64 bit .NET, you would need the 64 bit version.

The community package we are using does not install both 64 and 32 versions. Thanks for noticing this @emtuls! I propose we install dnspyex directly to fix this.

**Comment by Ana06** [comment]
I have tried to install this manually using the zips from https://github.com/dnSpyEx/dnSpy/releases/tag/v6.3.0, the log says that the zips are unzipped sucessfully, but the 32 folder is empty:

```
Downloading dnspyex.vm
  from 'https://github.com/dnSpyEx/dnSpy/releases/download/v6.3.0/dnSpy-net-win32.zip'

Download of dnSpy-net-win32.zip (81.9 MB) completed.
Hashes match.
Extracting C:\Users\flare\AppData\Local\ChocoCache\dnspyex.vm\6.3.0.20230605\dnSpy-net-win32.zip to C:\Tools\dnSpyEx32...
C:\Tools\dnSpyEx32
Added C:\ProgramData\chocolatey\bin\dnSpyEx32.exe shim pointed to 'c:\tools\dnspyex32\dnspy.exe'.
C:\Tools\dnSpyEx32\dnSpy.exe
Downloading dnspyex.vm
  from 'https://github.com/dnSpyEx/dnSpy/releases/download/v6.3.0/dnSpy-net-win64.zip'

Download of dnSpy-net-win64.zip (87.46 MB) completed.
Hashes match.
Extracting C:\Users\flare\AppData\Local\ChocoCache\dnspyex.vm\6.3.0.20230605\dnSpy-net-win64.zip to C:\Tools\dnSpyEx64...
C:\Tools\dnSpyEx64
Added C:\ProgramData\chocolatey\bin\dnSpyEx64.exe shim pointed to 'c:\tools\dnspyex64\dnspy.exe'.
C:\Tools\dnSpyEx64\dnSpy.exe
```

I am able to unzip `C:\Users\flare\AppData\Local\ChocoCache\dnspyex.vm\6.3.0.20230605\dnSpy-net-win32.zip` manually. Any idea what's going on?

**Comment by mr-tz** [comment]
`dnSpy-netframework.zip` contains 32- and 64-bit EXEs. Maybe we can use that?

**Comment by Ana06** [comment]
`dnSpy-netframework.zip` seems to work, thanks @mr-tz! 👍
