### ISSUE TITLE
[NuGet] not able to contact source "https://www.myget.orf/F/vm-packages/api/v2"

### ISSUE THREAD

**Issue by Amna-cpe** [mandiant/VM-Packages#416]
### What's the problem?

Choco Version 1.4.0
After encountering a disruption in the installation process, I installed Boxstarter with Choco. However, I am now facing an error whenever I attempt to install certain packages.

![image](https://github.com/mandiant/VM-Packages/assets/62321466/4387f609-278c-41ba-adac-341435f026ca)

`[NuGet] not able to contact source "https://www.myget.orf/F/vm-packages/api/v2"`

### Steps to Reproduce

1. download choco version 1.4.0
2. download boxstarter with choco `choco install boxstarted`
3.  run` ./install -password`

### Environment

VM OS is windows 10
VM Chocolatey version 1.4.0

### Detected by test suite

Yes

**Comment by mr-tz** [comment]
Hm, `not able to contact source` indicates a connection issue. Can you confirm networking works as expected?

**Comment by Amna-cpe** [comment]
> Hm, `not able to contact source` indicates a connection issue. Can you confirm networking works as expected?

I can access the URL in the browser, also there is no proxy enabled in this VM

![image](https://github.com/mandiant/VM-Packages/assets/62321466/77e08eae-ca91-4829-9a73-37798e12b1d3)

**Comment by mr-tz** [comment]
Can you also contact it from the terminal/PowerShell?

**Comment by Ana06** [comment]
I have just installed flare-vm with Chocolatey 1.14 and Boxstarter 3.0.1 and all packages install correctly for me. The daily GH action run is also working: https://github.com/mandiant/VM-Packages/wiki/Daily-Failures So I am not sure what the problem can be.

Can you please try the following command and post the output?
```
choco upgrade die.vm -y -r -s 'https://www.myget.org/F/vm-packages/api/v2;https://community.chocolatey.org/api/v2/' --force
```
