### ISSUE TITLE
Package proposal:  de4dot.vm (.NET tool)

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#418]
We have already de4dot-cex, but @mike-hunhoff recommended added [de4dot](https://github.com/de4dot/de4dot) as well in https://github.com/mandiant/VM-Packages/issues/247#issuecomment-1473993562 It seems there is no binary for de4dot and that we need to compile it during package installation.

**Comment by mr-tz** [comment]
Not sure if this could be an alternative (legally), but we could create a fork and add a release there to download?!

**Comment by emtuls** [comment]
@mr-tz @Ana06 Following up on this as I'm still not sure how to handle it. 

We've got a couple of packages that do not have releases and will require some sort of package release or compilation during install if we intend to use them. Primarily this package (de4dot) and `dnlib`.

**Comment by mr-tz** [comment]
We could create a package that builds at runtime, but I don't think the extra work is worth is currently (especially, since we have a de4dot fork package already).

**Comment by emtuls** [comment]
Opted for just using `de4dot-cex` instead of both versions.

https://github.com/mandiant/VM-Packages/pull/346
https://github.com/mandiant/VM-Packages/issues/247
