### ISSUE TITLE
Package proposal: GoResym.vm

### ISSUE THREAD

**Issue by stevemk14ebr** [mandiant/VM-Packages#434]
### Package Name

GoResym

### Tool Name

GoReSym

### Package type

ZIP_EXE

### Is the tool a console application?

true

### Tool's version number

2.4

### Category

Utilities

### Tool's authors

stevemk14ebr

### Tool's description

Go symbol recovery tool 

### Download URL

https://github.com/mandiant/GoReSym/releases/download/v2.4/GoReSym-windows.zip

### Download SHA256 Hash

6d253e98fce443b5c818e0ae0c0f0a4e3587e0f0f7baf150383ead242e01babd

### Why is this tool a good addition?

The tool is helpful to reverse engineers who need to recovery types and symbols from Go binaries.

**Comment by mr-tz** [comment]
Thanks, should be added very soon via #436!

**Comment by Ana06** [comment]
Thanks @stevemk14ebr!
