### ISSUE TITLE
Package proposal: upx.vm

### ISSUE THREAD

**Issue by tarterp** [mandiant/VM-Packages#440]
### Package Name

upx

### Tool Name

upx

### Package type

ZIP_EXE

### Is the tool a console application?

true

### Tool's version number

4.0.2

### Category

Utilities

### Tool's authors

markus-oberhumer

### Tool's description

UPX is a free, secure, portable, extendable, high-performance executable packer for several executable formats.

### Download URL

https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-win64.zip

### Download SHA256 Hash

325c58ea2ed375afbd4eeac0b26f15f98db0d75dea701205ca10d8bf4d2fdc24

### Why is this tool a good addition?

standard for unpacking UPX

**Comment by Ana06** [comment]
@mr-tz you had the idea of adding a `Packers` category: https://github.com/mandiant/VM-Packages/issues/38#issuecomment-1108157202 Should we do it?

I think there is no other packer that would need to be moved at the moment, so we should be fine. We have net-reactor-slayer, but I would keep it in dotNET.

**Comment by mr-tz** [comment]
I don't think so. upx gets run via the command-line anyway.

**Comment by Ana06** [comment]
But we should add a shortcut as well, right?

**Comment by Ana06** [comment]
@mr-tz are you then in favour or against adding the new category? 😕

**Comment by mr-tz** [comment]
I would not add it just for UPX and don't think we want to re-categorize other potential Packers tools currently.
A shortcut would be nice, but more importantly it's in the PATH so can be run easily from the command line.
