### ISSUE TITLE
The packages badge in README is not updated

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#455]
Since we moved the failures to the wiki, we are not updating the number of packages in the README. This label used to be updated with every daily run. I am going to send a PR to update the label manually to `>100`.

How should we update number of packages? Ideas:
1. when merging PRs using exactly numbers. Noisy but exact. We do it in this way in [capa](https://github.com/mandiant/capa-rules/blob/master/.github/workflows/sync.yml) but note that there the commit is needed to keep the repositories in sync.
2. Once a week (similarly as we do with the weekly updates) and using 10-increments (`>100`, `>110`, `>120`, etc.). We don't get the exact number but it is less noisy. It takes a week to update.
3. In the daily and using 10-increments (`>100`, `>110`, `>120`, etc.). We don't get the exact number but it is less noisy. It takes a day to update.

I like to use 10-increments (or we could even do 20-increments) as we don't get noisy commits every day this way. So I would go for option 3.

**Comment by mr-tz** [comment]
either option works for me

**Comment by Ana06** [comment]
I have changes my mind. I would like to get the exact number. It is a bit noisy and requires skipping branch protections for our bot, but I think it is worth it to get the exact number. We have been doing it in this way in capa for a long time.
