### ISSUE TITLE
Package idea: ida.plugins.vm

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#466]
Add package to install ida plugins such as capa explorer.

1. Should we have a package per plugin or just for all? I tend to think one is enough as ida plugins are normally not that big.
2. Which plugins should we install?

**Comment by Ana06** [comment]
I would like to install the capa plugin using FLARE-VM (adding it to the plugins directory) so that when you install IDA Pro, it is already there. The capa.vm package installs capa using the standalone binary. But to use it as a plugin, we need to install it as a python library using `pip`. @mr-tz @williballenthin @mike-hunhoff does it make sense to install it as both standalone binary and Python library? Or should we change to install it only as a Python library? The same applies to floss.

If we install it as both a standalone binary and as a Python library, should the Python package installation go into the libraries.python3.vm package and be required as dependency in the plugin package or should it go into the package that install the plugin? The difference is if we want it to always be installed in Python even if we don't install the plugin.

I am also not sure which package should install the capa plugin. Several options:

# Option 1
We add it to the `capa.vm` package. We can do the same for other tools like floss, but we would have to have a different ways for plugins without a standalone binary.

# Option 2
We create a `plugin.capa.vm` package. This implies one package per plugin, but allows users to decide which ones they want.

# Option 3
We create a `plugin.vm` package with several plugins. Users can't decide which plugins to install. But the simplification may be good and we can always split it in the future if needed.

@vm-packages opinions?

**Comment by williballenthin** [comment]
i love the idea of being able to use flarevm as an IDA Pro package manager (option 2)! i hadn't considered using flarevm selectively for only IDA but it makes so much sense. 

the capa plugin should include the pip library, the rules, and the plugin entry script. we should also try to pre-configure the rules location setting for ease of use. 

finally, i think capa.exe and the plugin should be separate. capa.exe comes with the embedded rules, signatures, etc that make it much easier to use than the source/library distribution.

**Comment by mike-hunhoff** [comment]
This is great @Ana06! +1 for everything Willi said doubly including my support for option [#]2, using FLARE VM as a IDA plugin manager (capa explorer, Diaphora, etc.). For capa explorer, follow the install instructions [here](https://github.com/mandiant/capa/tree/master/capa/ida/plugin#installation) and it's good to go.

@williballenthin I like your idea of pre configuring a rules directory - I suggest we code capa explorer to, by default, check a user's IDA plugins directory for capa rules if the user hasn't already configured rules. We already encourage users to install capa explorer to their IDA plugins directory so this seems like a natural location to also store the capa rules.

**Comment by Ana06** [comment]
Thanks for the feedback @williballenthin @mike-hunhoff!

@mike-hunhoff 
> Diaphora
We have already a package for Diaphora, but as diaphora is not a plugin at the moment it is installed in Utilities. Diaphora documentation says it is complicated to make it a plugin but I think it should be double to install it as a plugin that wraps the diaphora script. I'll take a look into this.

> pre-configure the rules location setting for ease of use
This was what I was thinking as well. Is there a way to do this at the moment? Or we need to modify the capa plugin?

> We already encourage users to install capa explorer to their IDA plugins directory so this seems like a natural location to also store the capa rules.
I am not sure if ida also checks directories in the plugins directory. Does someone know? I am just thinking if this could slow down IDA loading the plugins. If not, this sounds like a good idea.

**Comment by Ana06** [comment]
It doesn't look like there is a way to specify a path for the rules in CAPA explorer. If we want to hardcode the default, I think it is enough with adding a check for the default hardcoded path if `CAPA_SETTINGS_RULE_PATH` is empty and assign it. I think we can add this just after [`settings = ida_settings.IDASettings("capa")`](https://github.com/mandiant/capa/blob/240376153a533ff5a26b9b047502b41ce4feffe8/capa/ida/plugin/form.py#L49). Should I send a PR for this in capa?

**Comment by williballenthin** [comment]
the IDA plugin relies on ida-settings that will eventually end up using the registry, I believe. so, we could set the registry key that the plugin expects. alternatively, updating the plugin to guess a few typical paths makes sense, as long as we inform the user when making an assumption.
