### ISSUE TITLE
do not check the hash for signed packages

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#469]
Microsoft often distribute tools with a URL that doesn't include the version making the package break with every new update (as the hash changes). But I assume Microsoft signs the tools and we could use the signature as versification instead of the hash. This would prevent packages like sysinternals from breaking. @mandiant/flare-vm what do you think? Any ideas of how we can implement this? 🤔

**Comment by day1player** [comment]
This will be a relevant topic for the upcoming metasploit package as well. Metasploit releases "latest" msi installers every week.. Is this not something that CI/CD can check for us? If the hash is a mismatch, could we submit a PR?

**Comment by mr-tz** [comment]
1. If we can download and install packages without any hash we could do that for select packages (like the ones mentioned)
2. Alternatively, we create a CI step like @day1player suggests

2. sounds more correct, but 1. could be much easier

**Comment by Ana06** [comment]
> This will be a relevant topic for the upcoming metasploit package as well. Metasploit releases "latest" msi installers every week.. Is this not something that CI/CD can check for us? If the hash is a mismatch, could we submit a PR?

We could implement a CI that updates the hash (similar to the current update action) but still the package is broken for some time (from the moment it breaks after the PR is generated and merged), which is not ideal.  For community packages, the community updates the hash and CI updates the community package (for example sysinternals and chrome), but still the package is broken for some time.

Users have already the option to use the `--ignore-checksums` if they don't want to check the hash. 

**Checking signatures instead of hashes for signed packages would be IMO the best option. We probably can use [`sigverif.exe`](https://learn.microsoft.com/en-us/windows/win32/seccrypto/using-signtool-to-verify-a-file-signature) for this.**

**Comment by day1player** [comment]
@Ana06 I looked into this as well, there is a powershell function [`Get-AuthenticodeSignature`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-authenticodesignature?view=powershell-7.3) I was going to play around with we could probably wrap into an assert function.

**Comment by Ana06** [comment]
Packages that would benefit from this: sysinternal, cyberchef

**Comment by Ana06** [comment]
## Status summary
To address this issue we need to:
- Create a helper in common.vm to download/install a file checking its signature instead of the hash with chocolatey
- Use this helper in sysinternals.vm
- Create googlechrome.vm that uses this helper to install chrome. (then we can re-add the dependency in cyberchef: https://github.com/mandiant/VM-Packages/issues/296)
