### ISSUE TITLE
Add InnoSetup tools

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#472]
I would like to add the following two tools/packages:
- [IFPSTools](https://github.com/Wack0/IFPSTools) 
  - depends on the community package `php`
  - php has to be configured to use mbstring extension: remove the `;` of the line `;extension=mbstring` in the php.ini file (inside the php installation folder)
  - run it with `php DisIFPS.php <your_compiled_script_file> <output file>`
- [isdsetup.1.5.exe.zip](https://github.com/dscharrer/innoextract/files/5507287/isdsetup.1.5.exe.zip) which I found in https://github.com/dscharrer/innoextract/issues/106

We have already 2 InnoSetup tools (innoextract and innounp). With these two extra it is already 4. I propose creating a `InnoSetup` category. I think it makes sense as Utilities is getting big. Moving the two existent packages may be a breaking change that may break updates. But we are not testing updates anyway and we recommend to do new installs vs updating packages.

**Comment by mr-tz** [comment]
The site says: Superseded by [IFPSTools.NET](https://github.com/Wack0/IFPSTools.NET).

Let's use that instead?

**Comment by Ana06** [comment]
It seems to work also fine. We can use the zip in the releases. Do we want to create a shortcurt only for `ifpsdasm` or also for any of the other tools?
