### ISSUE TITLE
7-zip is not up to date

### ISSUE THREAD

**Issue by torabi12** [mandiant/VM-Packages#473]
### What's the problem?

config.xml uses 7-zip 15.05 beta package but the latest one is 23.01
https://www.7-zip.org/history.txt

### Steps to Reproduce

1. Install flare-vm
2.  check 7-zip version
3. compare it with the actual one

### Environment

VMware Workstation Pro 17.0.2
Windows 10 22H2 (latest)

### Detected by test suite

I don't know

**Comment by mr-tz** [comment]
Thanks, that's on purpose because that version can unpack NSIS scripts.
I realize it's not ideal though and would like to keep it up to date instead.
Maybe we can create two packages or have 15.05 as a backup (standalone EXE) saved to the application directory.

**Comment by torabi12** [comment]
15.05 is a very old version, I don't know how the system is working but maybe a backup standalone usage for a special task would be better and installing the actual release could make the VM more up to date for the user.

**Comment by mr-tz** [comment]
See the discussion in https://github.com/mandiant/VM-Packages/issues/87 😄 
Now you've asked for it, so we should proceed as outlined before.

**Comment by Ana06** [comment]
is there a case for which 7-zip 15.05 doesn't work? I am not sure if having two version of the tools will be more confusing for the users than having an outdated version. 🤔

**Comment by torabi12** [comment]
I didn't know that the old version is needed for special purpose. If I had known I would not have opened a ticket for the non-existent problem.
