### ISSUE TITLE
💡 Idea: Right click option to unzip with password infected

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#480]
Many malware analysis related zips have the password `infected`. What about adding the option to unzip with this password to the right menu to speed unzipping this kind of files to the 7-zip package?

**Comment by mr-tz** [comment]
To unzip, set:
    HKEY_CLASSES_ROOT*\shell\unzip "infected"\command
        "C:\Program Files\7-Zip\7z.exe" e -pinfected "%1"

https://moritzraabe.de/2023/06/05/windows-right-click-menu-shortcuts-open-with-ida/
