### ISSUE TITLE
Package proposal: jd-gui.vm

### ISSUE THREAD

**Issue by nos3curity** [mandiant/VM-Packages#533]
### Package Name

jd-gui

### Tool Name

jd-gui

### Package type

GITHUB_REPO

### Is the tool a console application?

false

### Tool's version number

1.6.6

### Category

Disassemblers

### Tool's authors

java-decompiler

### Tool's description

JD-GUI, a standalone graphical utility that displays Java sources from CLASS files.

### Download URL

https://github.com/java-decompiler/jd-gui/releases/download/v1.6.6/jd-gui-windows-1.6.6.zip

### Download SHA256 Hash

79c231399d3d39d14fce7607728336acb47a6e02e9e1c5f2fa16e2450c0c46cb

### Why is this tool a good addition?

for Commando

**Comment by mr-tz** [comment]
Note that we already have a bytecodeviewer package which includes the jd-gui decompiler.

**Comment by nos3curity** [comment]
@mr-tz my bad. Thanks for pointing this out.
