### ISSUE TITLE
Package proposal: mailsniper.vm

### ISSUE THREAD

**Issue by dumosuku** [mandiant/VM-Packages#544]
### Package Name

mailsniper

### Tool Name

MailSniper.ps1

### Package type

SINGLE_PS1

### Is the tool a console application?

true

### Tool's version number

0.0.0.20230712

### Category

Credential Access

### Tool's authors

dafthack

### Tool's description

MailSniper is a penetration testing tool for searching through email in a Microsoft Exchange environment for specific terms.

### Download URL

https://raw.githubusercontent.com/dafthack/MailSniper/f6fd1441feb246ba0d1c6d47f7f3a6dcbe3d2b92/MailSniper.ps1

### Download SHA256 Hash

353eec8f77c54fc914168bbdc111f0766421aaf8d7e4314036e79bf1b08060c6

### Why is this tool a good addition?

CommandoVM tool

**Comment by nos3curity** [comment]
Just fyi @dumosuku, the tool name shouldn't contain a file extension. Will fix your branch rn.
