### ISSUE TITLE
Package proposal: syswhispers3.vm

### ISSUE THREAD

**Issue by dumosuku** [mandiant/VM-Packages#549]
### Package Name

syswhispers3

### Tool Name

SysWhispers3

### Package type

GITHUB_REPO

### Is the tool a console application?

false

### Tool's version number

0.0.0.20230712

### Category

Payload Development

### Tool's authors

klezVirus

### Tool's description

SysWhispers helps with evasion by generating header/ASM files implants can use to make direct system calls.

### Download URL

https://github.com/klezVirus/SysWhispers3/archive/e3d5fc744c2e5c0ae952be0f7dcf498c5a68be4b.zip

### Download SHA256 Hash

987d04d404ee86536e04c488037fa9c9caa12d35fefdf9c0bc193d1bfed4c96a

### Why is this tool a good addition?

CommandoVM tool

**Comment by nos3curity** [comment]
@dumosuku please set console application to false. That only works with single executables, but this is a GitHub repo. Also add capitalization to "Tool Name", since that will be used in a shortcut. And add the 3 there.
