### ISSUE TITLE
CyberChef.vm

### ISSUE THREAD

**Issue by akram-alkhateeb** [mandiant/VM-Packages#603]
### What's the problem?

While installing Flare-VM, I kept running into installation failure (only 30 something packages installed) due to version dependency of cyberchef that requires Google Chrome version 114.0.5735.199 while the latest version is 115.x.x.x. 
I had to manually edit cyberchef.vm.nupkg and update the cyberchef.vm.nuspec file and edit the installed version of Google Chrome 

### Steps to Reproduce

installing flare-vm using the installation script (install.ps1)

### Environment

Dependency version mismatch, stops and refuse to install anything (even unrelated packages) due to CyberChef Requires Google Chrome 114.0.5735.199 (an outdated version) when the latest version is 115.x.x.x.

### Detected by test suite

I don't know

**Comment by mr-tz** [comment]
This should have been fixed in #626.
