### ISSUE TITLE
Use Env:ChocolateyToolsLocation

### ISSUE THREAD

**Issue by MalwareMechanic** [mandiant/VM-Packages#62]
https://github.com/mandiant/VM-Packages/blob/60e3edf97ee45faa12b380cf0ac17274aad4606b/packages/cygwin.vm/tools/chocolateyinstall.ps1#L31

When users update the default `${Env:RAW_TOOLS_DIR}` location it also modifies the `${Env:ChocolateyToolsLocation}` location and this is the location where Chocolatey defaults to install tools. For tools / dependencies that install to the default location, we need to use `${Env:ChocolateyToolsLocation}`.

**Comment by MalwareMechanic** [comment]
@mr-tz https://github.com/mandiant/VM-Packages/pull/138 closes this

**Comment by mr-tz** [comment]
sweet!
