### ISSUE TITLE
Failed to install: libraries.python3.vm

### ISSUE THREAD

**Issue by kasper45** [mandiant/VM-Packages#623]
### What's the problem?

Error installing libraries.python3.vm package.
The problem in stringsifter tool (part of libraries.python3.vm).

### Steps to Reproduce

clean installation

### Environment

windows 10 updated to latest version

**Comment by drgnz** [comment]
same here.

**Comment by kasper45** [comment]
[install_log.txt](https://github.com/mandiant/VM-Packages/files/12291429/install_log.txt)

**Comment by kasper45** [comment]
> What's the error message you're getting?

Building wheel for scikit-learn (PEP 517): finished with status 'error'

**Comment by godylockz** [comment]
Can confirm:
`[libraries.python3.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install Python 3.9 module: stringsifter`

**Comment by mr-tz** [comment]
We've disabled stringsifter for now in #645, so this shouldn't occur anymore.

**Comment by Ana06** [comment]
We can close this. Stringsifter being broken is tracked in https://github.com/mandiant/VM-Packages/issues/644
