### ISSUE TITLE
Stringsifter failing to install

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#644]
### What's the problem?

Stringsifter is not installing, causing other newly added Python packages to fail.
![stringsifter](https://github.com/mandiant/VM-Packages/assets/35854880/53f8cc30-dd7f-4705-85db-ffc01ea1cb04)

### Steps to Reproduce

1. Attempt to install all python libraries in libraries.python3.vm modules.xml

### Environment

Seems to be an issue across all environments.

### Detected by test suite

I don't know

**Comment by godylockz** [comment]
Can confirm:
` [libraries.python3.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install Python 3.9 module: stringsifter`

**Comment by emtuls** [comment]
@godylockz it should be fixed in main, from this PR which disabled stringsifter: https://github.com/mandiant/VM-Packages/pull/645

Keeping this issue open until a working fix occurs that adds stringsifter back into main.

**Comment by Ana06** [comment]
@emtuls can you please add the installation logs here (or link a CI run where it is failing as the log should be uploaded to the artifacts) so that we can see what the error is?

**Comment by emtuls** [comment]
@Ana06 here is one CI run of it falling: https://github.com/mandiant/VM-Packages/actions/runs/5941274882
