### ISSUE TITLE
Metapackage proposal: cherrytree.vm

### ISSUE THREAD

**Issue by godylockz** [mandiant/VM-Packages#654]
### Package Name

cherrytree

### Tool Name

cherrytree

### Package type

METAPACKAGE

### Tool's version number

1.0.1

### Category

Text Editors

### Tool's authors

giuspen

### Tool's description

cherrytree

### Dependency

N/A

### Shim path

%PROGRAMDATA%\chocolatey\bin

### Why is this tool a good addition?

Its used throughout the industry as a good note taking app.
https://github.com/giuspen/cherrytree

**Comment by Ana06** [comment]
@godylockz thanks for sharing this idea! But I am not sure this tool shouldn't be added to VM-Packages. It is possible to install it as a community package already and there is no need for a link in the tools folder (we don't add notepad++ to the folder for example). Is there anything extra that you think would make sense to configure in a VM package that is not already in the community package?

**Comment by godylockz** [comment]
> @godylockz thanks for sharing this idea! But I am not sure this tool shouldn't be added to VM-Packages. It is possible to install it as a community package already and there is no need for a link in the tools folder (we don't add notepad++ to the folder for example). Is there anything extra that you think would make sense to configure in a VM package that is not already in the community package?

Doesn't look like the community package is being actively updated to the latest version available off GitHub. https://community.chocolatey.org/packages/cherrytree

**Comment by Ana06** [comment]
In the issue you are purposing to install the package using the community package as a dependency. Have you used the wrong issue template?

**Comment by godylockz** [comment]
> In the issue you are purposing to install the package using the community package as a dependency. Have you used the wrong issue template?

In the original issue i'm proposing to use the official github repository [https://github.com/giuspen/cherrytree] which is currently at version v1.0.2 (current release). The community package which you suggested [https://community.chocolatey.org/packages/cherrytree] is currently not maintained at the moment and is at a older version of v0.99.49 which was released back in 2022.

**Comment by Ana06** [comment]
@godylockz you have used the metapackage issue template:
![Screenshot 2023-10-06 at 13 49 04](https://github.com/mandiant/VM-Packages/assets/16052290/6ee95f73-a27f-458b-9485-3ae87fc1ccfe)

Use the template to create a package from URL and provided the requested information to propose creating a package from the official GH repository as we can't use automation with the issue you created:

![Screenshot 2023-10-06 at 13 49 47](https://github.com/mandiant/VM-Packages/assets/16052290/ac1e4d8b-0a4e-4b19-a985-98bf0ff18075)
