### ISSUE TITLE
CI: send PR fails with "line 16: unexpected EOF while looking for matching `"'"

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#67]
### What's the problem?

See https://github.com/mandiant/VM-Packages/runs/8303111845?check_suite_focus=true#step:5:20

May be an issue with the line breaks?

### Steps to Reproduce

add `send PR` label to METAPACKAGE issue

### Environment

CI

### Detected by test suite

No

**Comment by Ana06** [comment]
The problem is the `'` in the description as we are using `'` to escape the json string. I have manually changed `'` by `''` in https://github.com/mandiant/VM-Packages/issues/66 and then the action work.
