### ISSUE TITLE
Package proposal: SingleFileExtractor.vm

### ISSUE THREAD

**Issue by sara-rn** [mandiant/VM-Packages#678]
### Package Name

SingleFileExtractor

### Tool Name

sfextract

### Package type

ZIP_EXE

### Is the tool a console application?

true

### Tool's version number

2.0.0

### Category

dotNet

### Tool's authors

Joery Droppers

### Tool's description

command-line utility to extract files from single file bundles in .NET

### Download URL

https://www.nuget.org/packages/sfextract/

### Download SHA256 Hash

51374bad07adc721cd0a33e921b46736533ef3a2fadf9cba78ef209ddfe1199d

### Why is this tool a good addition?

I have ran into malware that is a .NET bundle (single file deployment) that contains lots of dependencies and this tool will help extracting all and listing the dependencies a single file application has.
It might be also useful to install the SingleFileExtractor.Core NuGetPackage as well to use it programmatically: (https://github.com/Droppers/SingleFileExtractor/)

**Comment by Ana06** [comment]
Thanks for submitting the package proposal @sara-rn! 

Tool dependency: dotnet-6.0-sdk
