### ISSUE TITLE
Load windbg symbols

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#688]
From https://github.com/mandiant/VM-Packages/issues/252#issuecomment-1476121411 (got lost as we only installed windbg when we closed that issue):

> Load `explorer.exe`, it will take some time (~30min), but will load many symbols so that you don't have to wait when working on other samples.
> We can use [.reload /f](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/-reload--reload-module-).
> 
> Not sure if it should be part of the windbg.vm package or something like windbg.symbols.vm (so that we make downloading symbols optional).

I think I tend to prefer windbg.symbols.vm, other ideas?

**Comment by binjo** [comment]
That amount of storage for symbols is probably not ideal for distribution. `pdblister` looks great for a package candidate, and gives the user options to download after installation.

**Comment by schrodyn** [comment]
I would very much like to see symbols appearing in my FLARE-VM builds. Another alternative to downloading the symbols efficiently would be PDBReSym from the STrace project.

https://github.com/mandiant/STrace/blob/main/Rust/PDBReSym/src/main.rs#L437-L443

I've spoken with the author and depending on bandwidth and VM resources the tool completes downloading symbols in about 3 minutes =)

**Comment by stevemk14ebr** [comment]
+1 to Conor's comment, I maintain PDBReSym publicly as part of my STrace project. Afaik it is the _fastest_ tool to download and cache all windows symbols. It's written in rust so is safe, and is something we should probably include as FLARE-VM as a Misc tool. Then as part of the FLARE-VM build we can have it run with the `cachesyms` flag which will automatically enumerate all C:\Windows binaries and cache their symbols in a format identically to how windbg and other tools do with the cache in C:\symbols by default, use `cachefolder` flag to change this default.

**Comment by Ana06** [comment]
@mandiant/flare-vm which category should we add STrace to?

**Comment by schrodyn** [comment]
FLARE-VM would just need to run `PDBReSym.exe cachesyms` and it will do the job. It will recurse through, by default, through `C:\Windows\System32\` and download all symbols and store them into `C:\symbols`. See help below.

The only issue that I can see might be the fact that PDBReSym isn't shipped as a compiled executable in the STrace releases. Maybe this is something Stephen can amend? Otherwise, the rust language toolchain would need to be installed in FLARE-VM and `cargo build` executed for `PDBReSym` and the executable placed into a suitable PATH.

In my malware analysis VM I ran `PDBReSym.exe cachesyms` and it was done in around 5 minutes while I was typing this comment and formatting it =)

```
C:\Users\lmulligan\user\Tools>PDBReSym.exe -h
Usage: PDBReSym.exe [OPTIONS] [COMMAND]

Commands:
  symbolicate  Symbolicate the given logfile and write out the symbolicated version. May download PDBs as necessary
  cachesyms    Iterates the specified sysdir and downloads all PDBs concurrently
  getpdb       Downloads the PDB for the given PE file
  downloadpe   Rather than downloading a PDB, download a PE from the symbol server
  help         Print this message or the help of the given subcommand(s)

Options:
      --cachefolder <cachefolder>  Path to directory to cache PDBs [default: C:\symbols]
  -h, --help                       Print help

C:\Users\user\Downloads\Tools>PDBReSym.exe cachesyms -h
Iterates the specified sysdir and downloads all PDBs concurrently

Usage: PDBReSym.exe cachesyms [OPTIONS]

Options:
      --sysdir <sysdir>  Path to folder containing windows system binaries [default: C:\Windows\System32\]
  -h, --help             Print help

C:\Users\user\Downloads\Tools>
```

**Comment by schrodyn** [comment]
Just FYI, not sure how big my symbols folder was before I ran the tool, I already had a lot of symbols downloaded, but the size of the folder is now 8.96GB for my Windows 10 VM.

**Comment by Ana06** [comment]
@stevemk14ebr has confirmed he can provide the PDBReSym binary in ~1-2 weeks. We'll create a package that install it and run the command @schrodyn provided after that. :wink:

**Comment by Ana06** [comment]
@stevemk14ebr provided the binary we need in the last release: https://github.com/mandiant/STrace/releases/tag/v1.3.3, thanks @stevemk14ebr!
