### ISSUE TITLE
Post-Installation VM Package Installation Option

### ISSUE THREAD

**Issue by VelxusDev** [mandiant/VM-Packages#692]
I would like to suggest an enhancement request for FlareVM. Typically, some analysts would want to install some VM packages that they haven't picked during installation. I'm aware they can run command prompt and go for: `choco install [package name]`. Although, they would need to locate the shortcut / executable of the tool they installed and manually add it to their Tools folder.

Is there an existing method to automatically install a tool(s) from [VM-Packages](https://github.com/mandiant/VM-Packages) and place it under which directory was it linked to in the Tools directory?

Thanks!

**Comment by Ana06** [comment]
If you install any of the packages in https://github.com/mandiant/VM-Packages/tree/main/packages with `choco install <package name>` and that package creates a shortcut in the tool directory, you will have the tool in the Tools folder. In other words, it already works as you are requesting. Is there a concrete package you have tried to install for which this is not the case?

**Comment by VelxusDev** [comment]
Ok, just realized that python2.vm was removed from the VM-Packages, but testing out other packages was working fine as expected.

I tried installing for PEanotomist is throwing out an error as seen below:

![image](https://github.com/mandiant/VM-Packages/assets/15859331/e2850a4a-734c-426d-a7cd-af34129ddbee)

I'm not sure if this should be raised as a different issue or keep it in the same thread @Ana06 ?

**Comment by Ana06** [comment]
That error says that the url does not exist. That issue is detected by our [daily run](https://github.com/mandiant/VM-Packages/wiki/Daily-Failures). You are welcome to send a PR with a fix, but I think we don't need an issue for it.
