### ISSUE TITLE
installer.vm "Unable to find type [System.Drawing.Image]"

### ISSUE THREAD

**Issue by naacbin** [mandiant/VM-Packages#693]
### What's the problem?

When running FlareVM install.ps1 I get the following error :

```text
2023/10/16 06:17:29 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: installer.vm
2023/10/16 06:17:29 [installer.vm] chocolateyinstall.ps1 [+] ERROR : For each failed package, you may attempt a manual install via: choco install -y <package_name>
2023/10/16 06:17:29 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed package list saved to: C:\ProgramData\_VM\failed_packages.txt
2023/10/16 06:17:29 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Please check the following logs for additional errors:
2023/10/16 06:17:29 [installer.vm] chocolateyinstall.ps1 [+] ERROR :    C:\ProgramData\_VM\log.txt (this file)
2023/10/16 06:17:29 [installer.vm] chocolateyinstall.ps1 [+] ERROR :    %PROGRAMDATA%\chocolatey\logs\chocolatey.log
2023/10/16 06:17:29 [installer.vm] chocolateyinstall.ps1 [+] ERROR :    %LOCALAPPDATA%\Boxstarter\boxstarter.log
[-] Please check the following logs for any errors:
        [-] C:\ProgramData\_VM\log.txt
        [-] %PROGRAMDATA%\chocolatey\logs\chocolatey.log
        [-] %LOCALAPPDATA%\Boxstarter\boxstarter.log
2023/10/16 06:17:29 [installer.vm] vm.common.psm1 [+] ERROR : [ERR] Unable to find type [System.Drawing.Image].
At C:\ProgramData\chocolatey\lib\installer.vm\tools\chocolateyinstall.ps1:140 char:16
+         $img = [System.Drawing.Image]::FromFile($backgroundImage);
+                ~~~~~~~~~~~~~~~~~~~~~~
ERROR: Unable to find type [System.Drawing.Image].
The install of installer.vm was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\installer.vm\tools\chocolateyinstall.ps1'.
 See log for details.
```

It's seems related to this line of code : https://github.com/mandiant/VM-Packages/blob/main/packages/installer.vm/tools/chocolateyinstall.ps1#L140C9-L140C67

From the issue https://github.com/PowerShell/vscode-powershell/issues/219, a fix would be to load the assembly with `Add-Type -Assembly System.Drawing`.

### Steps to Reproduce

Install installer.vm

### Environment

VM OS version and Service Pack
-----
Version                 : 10.0.22621
BuildNumber             : 22621
OSArchitecture          : 64-bit
ServicePackMajorVersion : 0
Caption                 : Microsoft Windows 11 Enterprise Evaluation

VM OS RAM (MB)
-----
0

VM OS HDD Space / Usage
-----
DeviceID DriveType ProviderName      VolumeName   Size         FreeSpace
-------- --------- ------------      ----------   ----         ---------
C:       3                                        135704604672 73574252544

VM AV Details
-----
AntiVirusProduct classname does not exist...

VM PowerShell Version
-----
5.1.22621.2428

VM CLR Version
-----
4.0.30319.42000

VM Chocolatey Version
-----
2.2.2

VM Boxstarter Version
-----
Boxstarter|3.0.3
Boxstarter.Bootstrapper|3.0.3
Boxstarter.Chocolatey|3.0.3
Boxstarter.Common|3.0.3
Boxstarter.HyperV|3.0.3
Boxstarter.WinConfig|3.0.3

VM Installed Packages
-----
010editor.vm|14.0.0
7zip|23.1.0
7zip.install|23.1.0
7zip-15-05.vm|15.5.0.20230926
adobereader|2023.6.20320
apimonitor|2.13.0.20210213
apimonitor.vm|2.13.0.20220224
autohotkey|1.1.36.2
autohotkey.install|1.1.37.1
Boxstarter|3.0.3
Boxstarter.Bootstrapper|3.0.3
Boxstarter.Chocolatey|3.0.3
Boxstarter.Common|3.0.3
Boxstarter.HyperV|3.0.3
Boxstarter.WinConfig|3.0.3
capa.vm|6.1.0
chocolatey|2.2.2
chocolatey-compatibility.extension|1.0.0
chocolatey-core.extension|1.4.0
chocolatey-dotnetfx.extension|1.0.1
chocolatey-visualstudio.extension|1.11.1
chocolatey-windowsupdate.extension|1.0.5
Cmder|1.3.24
cmder.vm|1.3.24
common.vm|0.0.0.20230926
cyberchef.vm|10.5.2.20230823
Cygwin|3.4.9
cygwin.vm|3.4.9
debloat.vm|0.0.0.20230904
dependencywalker|2.2.6000.9
dependencywalker.vm|2.2.6000
die.vm|3.7.20230925
dnspyex.vm|6.4.1
dotnet-6.0-desktopruntime|6.0.23
dotnet-6.0-runtime|6.0.23
dotnetfx|4.8.0.20220524
explorersuite.vm|0.0.0.20230925
fakenet-ng.vm|1.4.11.20230418
Firefox|118.0.2
floss.vm|2.3.0
ghidra|10.3.3
ghidra.vm|10.3.3.20230920
hashmyfiles.vm|0.0.0.20230925
hollowshunter.vm|0.3.6
hxd|2.5.0
hxd.vm|2.5.0.20230925
idafree.vm|8.3.0
KB2919355|1.0.20160915
KB2919442|1.0.20160915
KB2999226|1.0.20181019
KB3033929|1.0.5
KB3035131|1.0.3
KB3063858|1.0.0
KB3118401|1.0.5
map.vm|0.0.0.20230723
msys2|20230718.0.0
netfx-4.8|4.8.0.20220524
netfx-4.8-devpack|4.8.0.20190930
notepadplusplus|8.5.7
notepadplusplus.install|8.5.7
notepadplusplus.vm|8.5.7
notepadpp.plugin.compare.vm|2.0.2
npcap.vm|1.72.20230614
openjdk|21.0.0
openssh|8.0.0.1
pebear|0.6.5.2
pebear.vm|0.6.5.20230308
peid.vm|0.95.0.20221115
pesieve|0.3.6
pesieve.vm|0.3.6
pestudio.vm|9.55.0
powershell-core|7.3.8
processdump.vm|2.1.1.20220908
processhacker.install|2.39.0
regshot.vm|1.9.1
rundotnetdll.vm|2.2.0.20230526
sysinternals|2023.9.29
sysinternals.vm|2023.9.29
uniextract2.vm|2.0.0.20220113
vcbuildtools.vm|0.0.0.20231005
vcredist140|14.36.32532
vcredist2010|10.0.40219.32503
visualstudio2017buildtools|15.9.57
visualstudio2017-workload-vctools|1.3.3
visualstudio-installer|2.0.3
windbg.vm|0.0.0
wireshark|4.0.10
wireshark.vm|4.0.10
x64dbg.ollydumpex.vm|1.80.0
x64dbg.scyllahide.vm|0.0.0.20210823
x64dbg.vm|2021.5.8.20230418
x64dbgpy.vm|1.0.56.20211021
yara|4.3.2
yara.vm|4.3.2

Common Environment Variables
-----
VM_COMMON_DIR: C:\ProgramData\_VM
TOOL_LIST_DIR: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Tools
RAW_TOOLS_DIR: C:\Tools

### Detected by test suite

I don't know

**Comment by Ana06** [comment]
I forgot to add the classes from the `System.Drawing` .NET assembly in https://github.com/mandiant/VM-Packages/pull/683 🙈 Thanks for the detailed bug report @naacbin!
