### ISSUE TITLE
Improve "Open with IDA" to right click menu implementation

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#694]
At the moment we are using a PowerShell script to look for the latest version of IDA (potentially the Pro version installed after the ida.vm package). But there is no way to not show the PowerShell console (without a wrapper program). I think there are better ways to implement this.

Idea: Implement a binary launcher that starts the latest version of IDA (as the PowerShell script does). This has the advantage that we can also ping the binary to the taskbar and use it in the Tools folder.

Opinions? Other ideas?

**Comment by williballenthin** [comment]
https://github.com/namazso/IDAShell

**Comment by Ana06** [comment]
This can also be used to pin the correct ida to the taskbar

**Comment by Ana06** [comment]
I wonder if we can ping IDAShell to the taskbar, the we dont need to create a binary (assuming IDAShell is working as described in the first comment, I haven't tried).

**Comment by emtuls** [comment]
Initial PR for this is up: https://github.com/mandiant/VM-Packages/pull/758
