### ISSUE TITLE
Remove PS_Transcripts from Desktop

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#706]
@mandiant/commando-vm why are you logging PS to the Desktop? https://github.com/mandiant/VM-Packages/blame/3e31720901e68b02683cfbe014421c28500224c7/packages/common.vm/tools/vm.common/vm.common.psm1#L1149

I find it annoying to get this folder every time I open PowerShell, trying to figure when/where to disable this or if there is a good reason to keep it. @mandiant/flare-vm opinions?

**Comment by day1player** [comment]
I guess just to make it easy to find. I'm happy to relocate it if we can find another convenient spot. I'm sure you guys dont use the logging as much as we do, but I use the logs almost every engagement I'm on for timestamps, screenshots, command syntax, etc.

**Comment by day1player** [comment]
My suggestion if we moved it would be the Start Menu

**Comment by Ana06** [comment]
@day1player what about moving it and pin it to the taskbar (if it is possible to implement, see https://github.com/mandiant/VM-Packages/issues/708)?

**Comment by Ana06** [comment]
@day1player what about removing VM-Configure-PS-Logging and moving it to the commando-vm config file?

**Comment by Ana06** [comment]
@mandiant/flare-vm do you see a use case of having logging enabled for us?

**Comment by MalwareMechanic** [comment]
I vote we keep it, but let's move it if it's an annoyance on the desktop

**Comment by Ana06** [comment]
@mr-tz also mentioned he doesn't find it annoying. Ok, let's keep it for now and we can discuss removing at a later point if needed.
