### ISSUE TITLE
Add helper to pin to taskbar

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#708]
It would be nice to have a helper function in common VM-Pin-To-Taskbar to be able to configure the tools to pin in the configuration file. See https://github.com/mandiant/flare-vm/issues/512

I am not sue how to implement it though, as it seems this information is stored a bit cryptic in the register.

**Comment by day1player** [comment]
@Ana06 there is a chocolately package that we use to rely on for Commando: https://community.chocolatey.org/packages/syspin

I think what we might be able to do is incorporate this into the VM-Pin-To-Taskbar function:
https://github.com/SebastianK90/chocolateyautomaticpackages/blob/master/syspin/tools/chocolateyInstall.ps1

We can pull down the file, iterate through an array of items to pin to the taskbar, and then call the function in our configs so we can each have separate items pinned

**Comment by day1player** [comment]
Also not to hijack the issue, but I am also tracking these functions for the common module:

REMOVE FROM COMMON.VM:
- VM-ConvertFrom-Json
- VM-Get-DiskSize
- VM-Get-FreeSpace
- VM-Check-Reboot


ADD TO COMMON.VM
- VM-Pin-To-Taskbar
- VM-Assert-Signature
- VM-Add-To-Right-Click-Menu
- VM-Remove-Desktop-Shortcut

**Comment by Ana06** [comment]
> @Ana06 there is a chocolately package that we use to rely on for Commando: https://community.chocolatey.org/packages/syspin

This is a great thing @day1player. I can require it already in flare-vm as package and use to pin the tools. But I think a helper function would be better, as we can do this with a single line in the config. But even more important, I would like to have some tools to start with admin rights. I think we can't do this with syspin, or have I missed this?

Maybe this project is also useful: https://github.com/0x546F6D/pttb_-_Pin_To_TaskBar

**Comment by Ana06** [comment]
I think it would also be nice to pin the Tools folder to taskbar (if possible). I think this could be done in the debloat/installer package as I think this would be nice for commando-vm as well. Am I right? This is also a more complicated case as we need to change the directory to open.

**Comment by day1player** [comment]
> But even more important, I would like to have some tools to start with admin rights. I think we can't do this with syspin, or have I missed this?

I would very much like this as well, I might have to do some digging in the Commando 2.0 folders.. I think what we did was create a Chocolatey Shortcut (since that supports the `-RunAsAdmin` flag) and then we used syspin to pin that shortcut to the taskbar

> I think it would also be nice to pin the Tools folder to taskbar (if possible). I think this could be done in the debloat/installer package as I think this would be nice for commando-vm as well. Am I right? This is also a more complicated case as we need to change the directory to open.


I'm also a big fan of this, it would give us a completely clean desktop

**Comment by Ana06** [comment]
This was addressed in https://github.com/mandiant/VM-Packages/pull/748, thanks @emtuls!
