### ISSUE TITLE
Re-structure & improve documentation

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#728]
### Details

We have a lot of documentation in the Wiki, but I find it difficult to navigate. Reorganise the wiki documentation (and maybe remove/summarize some part).

**Comment by Ana06** [comment]
I have just done in a big update to the documentation, adding some important details that come up often in discussions but also simplifying it and restructuring to hopefully make it easier to use. @mandiant/vms @naacbin @MalwareMechanic any feedback? Can we close this issue?

**Comment by naacbin** [comment]
I have read both [Chocolatey-packages](https://github.com/mandiant/VM-Packages/wiki/Chocolatey-packages) and [Coding-Conventions](https://github.com/mandiant/VM-Packages/wiki/Coding-Conventions#small-pull-requests) documentation, it's really good. I have nothing to add. Thanks for this work !

**Comment by Ana06** [comment]
Thanks for the review @naacbin!
