### ISSUE TITLE
Resource Hacker fails to install

### ISSUE THREAD

**Issue by xplt-artur** [mandiant/VM-Packages#739]
### What's the problem?

I hope im at the right place! If not, feel free to close and ideally tell me the right place.

I just installed a CommandVM and noticed the following broken packages:

For the default Victim Package List:

`2023/11/09 22:51:29 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: sysinternals`
`2023/11/09 22:51:29 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: sysinternals.vm`
`2023/11/09 22:51:30 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: resourcehacker.portable`
`2023/11/09 22:51:30 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: resourcehacker.vm`

sysinternals:

`
Checksum for 'C:\Users\Artur\AppData\Local\ChocoCache\sysinternals\2023.10.18\SysinternalsSuite.zip' did not meet '06a8a45fb8c8c76879b6a7635eaccb6a7c662be8ada2448ff889a7961808a857' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
`

resourcehacker.portable:

`
ERROR: Checksum for 'C:\Users\Artur\AppData\Local\ChocoCache\resourcehacker.portable\5.1.8\resource_hacker.zip' did not meet 'D158BEBC2993CF6BEBF2C23A93572A68544C2BA5AE056538F70A58075C9392D6' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
`

For the default offensive variante:

`2023/11/09 19:53:46 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: rubeus.vm`
`2023/11/09 19:53:46 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: tor-browser`
`2023/11/09 19:53:46 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: resourcehacker.portable`
`2023/11/09 19:53:46 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: situational-awareness-bof.vm`
`2023/11/09 19:53:46 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: tor-browser.vm`
`2023/11/09 19:53:46 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: vscode.install`
`2023/11/09 19:53:46 [installer.vm] chocolateyinstall.ps1 [+] ERROR : Failed to install: resourcehacker.vm`

rubeus:

`
2023/11/09 22:59:06 [rubeus.vm] vm.common.psm1 [+] ERROR : Checksum for 'C:\Users\Artur\AppData\Local\ChocoCache\rubeus.vm\2.2.3\Rubeus-master.zip' did not meet 'DC61768AF588A5FCC1CEDC491E8DF81BC652A96A1A032741034E40B75EC404F2' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
`

tor-browser:

Tries to get 12.5.X, but only 13.X branch is still offered for download (https://www.torproject.org/dist/torbrowser/)

`
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.torproject.org/dist/torbrowser/12.5.6/torbrowser-install-win64-12.5.6_ALL.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
`

situational-awareness-bof:

`
ERROR: Checksum for 'C:\Users\Artur\AppData\Local\ChocoCache\situational-awareness-bof.vm\0.0.0.20230713\CS-Situational-Awareness-BOF-master.zip' did not meet 'e3673d7e41ad6d36ca7d6d44821f68238aae9968e062acb6d96fc7663c87bbdb' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
`

vscode.install:

This one works manually, but doesnt get even tried when using the install.ps1 script. (still is listed as failed though)

### Steps to Reproduce

-

### Environment

VMWare Workstation 17.0.2
Windows 22H2

Everything else default with a fresh installer out of the Repo.

### Detected by test suite

I don't know

**Comment by MalwareMechanic** [comment]
Resource Hacker fixed in https://github.com/mandiant/VM-Packages/pull/741
Sysinternals fixed in https://github.com/mandiant/VM-Packages/pull/740

**Comment by day1player** [comment]
@xplt-artur I would recommend attempting to reinstall the packages that failed manually, it looks to me like something might have been happening during the install with the download integrity being messed up. If you do attempt to install manually please let me know if the issues persist.

**Comment by day1player** [comment]
Issues have been fixed, no similar new issues have been reported.. Please let us know if you are still having issues
