### ISSUE TITLE
Merge  `VM-Install-From-Zip` and `VM-Install-Raw-GitHub-Repo`

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#749]
### Details

From https://github.com/mandiant/VM-Packages/pull/727>
> The code of the `VM-Install-From-Zip` and `VM-Install-Raw-GitHub-Repo` is very similar, which is not surprising as a GitHub-Raw install is the same as installing a Zip.

Any thoughts about merging these two functions?

**Comment by Ana06** [comment]
It may make sense to address it together with https://github.com/mandiant/VM-Packages/issues/674

**Comment by day1player** [comment]
What about configuring an alias? Then we can leave all packages as they are. I like that they are named separately since people might not know automatically that they are the same

**Comment by Ana06** [comment]
A raw GH package is just a Zip that we download from GH. There is no difference at all with Zips we download from somewhere else. I think having both causes confusion. `VM-Install-From-Zip` has been lately improved and supports more options. I would like to get rid of `VM-Install-Raw-GitHub-Repo` both in the code and in the issues template and script to create packages. I think this will allow us to add some of the options to the issue template easily.

Proposal to progressively implement this (in different PR to be sent only after the previous steps have been merged):

- [ ] Merge `VM-Install-From-Zip` and `VM-Install-Raw-GitHub-Repo` into `VM-Install-From-Zip` but leave `VM-Install-Raw-GitHub-Repo` as a wrapper/alias that just calls `VM-Install-Raw-GitHub-Repo` so that we don't have to modify all the packages using `VM-Install-Raw-GitHub-Repo`
- [ ] Modify the script to generate packages, the issue template, and GH integration to only use `VM-Install-From-Zip`
- [ ] Update all the packages to use `VM-Install-From-Zip`

**Comment by Ana06** [comment]
@emtuls would you like to work on this? You have worked on the shortcuts lately that are related. :wink:

**Comment by Ana06** [comment]
This issue is not fixed. WE have simplified `VM-Install-Raw-GitHub-Repo` in #959, but the objective is to get rid of it completely. Steps needed to close this PR:
- [ ] Modify the script to generate packages, the issue template, and GH integration to only use `VM-Install-From-Zip`
- [ ] Update all the packages to use `VM-Install-From-Zip`

**Comment by Ana06** [comment]
@emtuls you have forgotten one package: https://github.com/mandiant/VM-Packages/blob/main/packages/minidump.vm/tools/chocolateyinstall.ps1#L10

**Comment by Ana06** [comment]
minidump fails to install, so documented the existent issue to fix it, as it is unrelated with this issue: https://github.com/mandiant/VM-Packages/issues/830#issuecomment-2051984201
