### ISSUE TITLE
Delete PS_Transcripts in VM-Remove-DesktopFiles

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#755]
### Details

I would like to delete the `PS_Transcripts` folder in the `VM-Remove-DesktopFiles` function (called by `VM-Clean-Up`) as I want to delete any log files (including PowerShell logs) when executing this function. However, as explained in https://github.com/mandiant/VM-Packages/pull/754, deleting `PS_Transcripts` while Powershell is open is an issue as `VM-Remove-DesktopFiles`/`VM-Clean-Up` are PowerShell functions. @emtuls any ideas how we could do this? I wouldn't like to complicate it the logic/code too much, but it would be nice to have.

**Comment by Ana06** [comment]
One relatively simple idea is to delete files in the directory if deleting the whole directory is not possible, this may delete part of the files in `PS_Transcripts`

**Comment by day1player** [comment]
I remember us discussing this in #706 , I think maybe we should just move PS_Transcripts folder to the Start Menu

**Comment by day1player** [comment]
Ok got it, that makes sense!
