### ISSUE TITLE
Package proposal: bytecodeviewer.vm

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#76]
### Package Name

bytecodeviewer

### Tool Name

Bytecode Viewer

### Tool's version number

2.11.2

### Category

Java

### Tool's authors

Konloch

### Tool's description

A lightweight user-friendly Java/Android Bytecode Viewer, Decompiler and more.

### Package type

ZIP_EXE

### Download URL

https://github.com/Konloch/bytecode-viewer/releases/download/v2.11.2/Bytecode-Viewer-2.11.2.jar

### Download SHA256 Hash

536ad387424106083f76cd0cb7c051a22aff21f08663ba2539c11f1ddef9147f

### Why is this tool a good addition?

To analyze Java/Android files.

**Comment by Ana06** [comment]
This is not a ZIP file with an exe. The `.jar` is the executable itself, right? I think the script doesn't support this kind of files at the moment. But I think it would be a good idea to extend it. I think @MalwareMechanic had some ideas to extend that script for several package types some time ago. But I don't find an issue, did we forget to create one @MalwareMechanic? 😕 What package types should we add?

**Comment by Ana06** [comment]
@MalwareMechanic I have created an issue for this package time https://github.com/mandiant/VM-Packages/issues/93

are we missing any other common package type?

**Comment by MalwareMechanic** [comment]
Since this is a `.jar` it needs to be launched via Java and I remember there were some tricky workarounds to get it right, see https://github.com/mandiant/VM-Packages/wiki/Common-Issues#workaround. We could create a special JAR template for these. Thoughts? @Ana06

**Comment by MalwareMechanic** [comment]
Besides `.jar`, I don't know of many more "types" we should add at the moment

**Comment by mr-tz** [comment]
I tested and think running it plain also worked.

**Comment by Ana06** [comment]
does the current `SINGLE_EXE` work for this case? 🤔

**Comment by MalwareMechanic** [comment]
I'll experiment tomorrow and ping back

**Comment by mr-tz** [comment]
Confirmed again that simply running `Bytecode-Viewer-2.9.22.jar` works.

**Comment by MalwareMechanic** [comment]
Yup, it seems as long as you have the java runtime installed Windows extension magic takes over and executes it correctly. I revived the old PR (#76) and updated it
