### ISSUE TITLE
`test_uninstall.ps1` doesn't work

### ISSUE THREAD

**Issue by naacbin** [mandiant/VM-Packages#763]
### What's the problem?

`test_uninstall.ps1` doesn't uninstall any packages. Moreover, although the documentation indicates the possibility of [uninstalling a specific package](https://github.com/mandiant/VM-Packages/wiki/Testing#package-uninstallation), the current script don't handle it.

I added the following parameters at the top of the file to remove package individually:

```powershell
param ([string] $package_names=$null, [switch] $all)
```

Then, I changed `$built_pkgs =...` to `$built_pkgs = $package_names`. However, this isn't an optimal solution.

### Steps to Reproduce

Run `scripts/test/test_uninstall.ps1` with or without `<package.vm>` args.

### Environment

VM OS version and Service Pack
-----
Version                 : 10.0.22621
BuildNumber             : 22621
OSArchitecture          : 64-bit
ServicePackMajorVersion : 0
Caption                 : Microsoft Windows 11 Enterprise Evaluation

VM AV Details
-----
AntiVirusProduct classname does not exist...

VM PowerShell Version
-----
5.1.22621.1778

VM CLR Version
-----
4.0.30319.42000

VM Chocolatey Version
-----
2.2.2

VM Boxstarter Version
-----
Boxstarter|3.0.3
Boxstarter.Bootstrapper|3.0.3
Boxstarter.Chocolatey|3.0.3
Boxstarter.Common|3.0.3
Boxstarter.HyperV|3.0.3
Boxstarter.WinConfig|3.0.3

### Detected by test suite

No

**Comment by naacbin** [comment]
I've tested it with a new machine and it seems fine.

**Comment by emtuls** [comment]
I know this is closed, but I believe I ran into this issue when I was using `test_uninstall.ps1` before, because a random folder called 'False' was being created inside `built_pkgs` unintentionally and when running this script, it would automatically fail and not uninstall my package.

This should hopefully be fixed from this PR: https://github.com/mandiant/VM-Packages/issues/839
