### ISSUE TITLE
New package: offvis.vm

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#791]
### Details

Microsoft OffVis

**Comment by Ana06** [comment]
@KJaeYoung is familiar with this tool and is able to answer any possible question about how to install/use this tool. 😃

**Comment by d35ha** [comment]
This tool requires .NET Framework 3.5 and trying to install the [choco version](https://community.chocolatey.org/packages/DotNet3.5) fails.
@Ana06 any ideas?

**Comment by d35ha** [comment]
@Ana06 
It's working now (idk why it didn't work at first), please test it extensively.
