### ISSUE TITLE
Set Chrome as default for opening .html files

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#823]
### Details

@binjo has proposed a way to set Chrome to default for .html files in https://github.com/mandiant/VM-Packages/pull/779, but it doesn't work for me in an empty environment. @binjo's proposal uses https://github.com/DanysysTeam/PS-SFTA

I think we may want to add this to `googlechrome.defaultbrowser.vm` instead of to `googlechrome.vm`. Related: https://github.com/mandiant/VM-Packages/issues/822

**Comment by Ana06** [comment]
We should check with legal if the decide to include https://github.com/DanysysTeam/PS-SFTA in the repository.

**Comment by stevemk14ebr** [comment]
It seems this is MIT licensed which makes me think it's ok legally

**Comment by stevemk14ebr** [comment]
bottom of the readme says it's MIT which is enough

**Comment by emtuls** [comment]
I just looked into this. This is mostly solved by the PR I made here: https://github.com/mandiant/VM-Packages/pull/1016

We can use the new helper function: `VM-Set-Open-With-Association <path to chrome> ".html"`, and after digging a bit deeper, I found that if we remove `MSEdgeHTM` from `HKCU` and `HKLM`, then it works. :)

I added it as a second commit to the PR

**Comment by emtuls** [comment]
Did we determine if this is something we can use or at least take a part of the code to use in our own way?
