### ISSUE TITLE
Fix Metasploit

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#828]
### Details

`https://windows.metasploit.com/metasploitframework-latest.msi` is signed. Use the new `VM-Assert-Signature` function to fix (and avoid that it fails again with every update) Metasploit similarly as we have done with Google Chrome in https://github.com/mandiant/VM-Packages/pull/824

**Comment by Aduno** [comment]
Checksum mismatch observed again for metasploit.vm installation with metasploitframework-latest.msi
