### ISSUE TITLE
Remove minidump.vm

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#830]
### Details

The url that we were using to downloading MiniDump is not available anymore: https://github.com/Mr-Un1k0d3r/MiniDump/archive/98a21941831b90b203fdbfb253cd0b3dc27a0475.zip :anguished:

@Mr-Un1k0d3r is there other url we can use to install MiniDump? 😊 

Otherwise we will have to get rid of this package. 😢

**Comment by man715** [comment]
I was able to find this one but honestly not sure how out-of-date it is. 

https://github.com/rvrsh3ll/MiniDump

**Comment by Ana06** [comment]
@mandiant/commando-vm should we use that version or get rid of this package?

**Comment by Ana06** [comment]
To fix this package we would need to replace `VM-Install-Raw-GitHub-Repo` by `VM-Install-From-Zip`, as this function has been removed in https://github.com/mandiant/VM-Packages/pull/988

**Comment by emtuls** [comment]
Also to note, that version does not have a release build on github.

**Comment by geo-lit** [comment]
Commando-VM is good to bin the package.

**Comment by Ana06** [comment]
Fixed in https://github.com/mandiant/VM-Packages/pull/1105
