### ISSUE TITLE
Removing messagebox at the end of installation script.

### ISSUE THREAD

**Issue by l33th4xor1** [mandiant/VM-Packages#837]
### Details

I have a use case for the CLI only mode for the FlareVM Installer. Unfortunately, whenever I run it, it tries to spawn a messagebox at the end of installation despite being in CLI mode. This is quite annoying. Would it be possible to either remove this or add an option to auto-ack that box?

https://github.com/mandiant/VM-Packages/blob/e8af7325958bb1a3f38f6f306c24a4fb2b74ef18/packages/installer.vm/tools/chocolateyinstall.ps1#L196C1-L245C1

**Comment by Ana06** [comment]
@l33th4x0rjs can you elaborate why is this exactly a problem?

I would agree to remove this message box, even in the normal mode. I think you are not able to select information from the message box, which doesn't make it the best place to display log paths. 🤔  I suggested modifying the box in https://github.com/mandiant/VM-Packages/pull/690, but @mandiant/commando-vm had some concerns. 

@mandiant/commando-vm  what are your thoughts about removing the message box in the CLI? what about removing it completely?

**Comment by Ana06** [comment]
@l33th4x0rjs thanks for the detailed explanation! We have also started automating malware analysis VM builds (reason why we have introduced features like the [CustomStartLayout](https://github.com/mandiant/flare-vm/blob/main/CustomStartLayout.xml) recently, which means this is going to be a problem for as well.

> Being able to get rid of any components that require a GUI when running the installer in CLI mode would be very useful for that reason. I think here you could just print the information usually contained in the dialog box to console instead?

I think this should work. @mandiant/commando-vm are you ok with removing the message box from the installer package?

Unrelated to this issue: @l33th4x0rjs could you provide some more details (maybe in a different issue in the flare-vm repo) about how you are implementing this automated builds. We could exchange some ideas and I wonder if it would be useful for the community to add an/some automated builds scripts to flare-vm (any thoughts would be appreciated).

**Comment by day1player** [comment]
Yeah I'm ok with that for sure. There is probably a nicer way to do it, I didnt anticipate the message box causing an issue.. When we rebuilt the Commando installer we added a `-cli` flag, maybe we could have that write a file to %VM_COMMON_DIR% and if we detect a CLI install we dont pop the box?

**Comment by day1player** [comment]
I will add that having the message box and playing that sound definitely adds to the user friendliness.. Before we had the message box we received a lot of issues and feedback about when the install was complete.

**Comment by mr-tz** [comment]
Ok, no worries. Thanks for sharing and for the improvements and ideas!

**Comment by day1player** [comment]
@l33th4xor1 out of curiosity are you doing anything to disable defender prior to the install?

**Comment by RexChenjq** [comment]
Just found this issue after submitting my [PR](https://github.com/mandiant/VM-Packages/pull/956)

Unlike other output using `Write-Host`, this `$form.ShowDialog()` is expecting a user to click the button before the powershell script can exit successfully. This is blocking unattended installation and image building in a full IAC/CICD environment.

**Comment by RexChenjq** [comment]
> @l33th4xor1 out of curiosity are you doing anything to disable defender prior to the install? That was one of my big hangups when it came to automating the cli unattended install

This worked for me
`Uninstall-WindowsFeature -Name Windows-Defender`
This requires a restart
