### ISSUE TITLE
VM-Install-Shortcut incorrectly uses 'RunAsAdmin' argument

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#839]
### What's the problem?

The function `VM-Install-Shortcut` is utilizing the `RunAsAdmin` argument for `Install-ChocolatelyShortcut` incorrectly leading to many unexpected issues such as:
- Some shortcuts that are created automatically have the "Comment" section filled in with 'false' or 'true' (depending what was passed in), which displays when hovering over the shortcut
- Every shortcut that is created will always be set to `run as admin` regardless of either `$true` or `$false` being passed in because the `RunAsAdmin` argument for `Install-ChocolatelyShortcut` is a `switch` rather than a `bool`.
- There is sometimes the creation of a `False` directory in `built_pkgs` inside of the `VM-Packages` directory
- Some shortcuts may have other things automatically set to "False" or "True" in their properties unintentionally 
  - for example, the `Start in:` is set to "False" for `hashmyfiles`

This is because the `RunAsAdmin` argument is a `switch`, but we are treating it like a `bool`

### Steps to Reproduce

Install any package that creates a shortcut and look at it's properties.

### Environment

Environment independent.

**Comment by Ana06** [comment]
Good catch!
