### ISSUE TITLE
Add "WindowStyle" argument to "VM-Install-Shortcut"

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#843]
### Details

Right now we have no way of modifying the Window Style for our shortcuts.

Having the ability to change the Window Style to `Minimized` or `Hidden` (which doesn't seem to actually work...) for console applications would make for a much nicer shortcut and this is supported by the `Install-ChocolatelyShortcut` function that we are using. (For example, it should alleviate seeing any command prompt popup that may not be wanted)

I think we should add this as an extra argument to pass into `VM-Install-Shortcut`.

**Comment by Ana06** [comment]
Is this needed for the CyberChef link? Thinking on the use of case. 🤔

**Comment by emtuls** [comment]
That is one of the reasons that I would like to have the options, yes. 🙂

I attempted to try the route of adding cyberchef to be the default homepage when opening chrome programmatically (modifying config files) but it seems to change often enough that it will likely break eventually.
Adding it as a chrome policy also didn't work as chrome straight up denies having a local file be used for the default homepage.

**Comment by emtuls** [comment]
While it may be nice to have, it's not a necessity right now as no tool currently needs it, so we can close it for the moment and reopen it if the need arises in the future. 🙂
