### ISSUE TITLE
Document local testing setup

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#851]
### Details

Several people has asked me what is my local testing setup.

For testing new packages I recommend to:
- using an empty windows
- install flare-vm with a configuration with just one simple package (for example hashmyfiles.vm)
- Copy the script `test_install.ps1` to the Desktop and create a folder `packages` in the Desktop
- Take a snapshot `testing`
- Every time you test a new package, revert to `testing`, copy the package to test to the `packages` folder and run the `test_install.ps1` script

This way you ensure that all needed dependencies are installed. 

Document also how to test pinging of icons to taskbar.

@vm-packages anything else regarging local testing that should be documented?

Related https://github.com/mandiant/VM-Packages/issues/728

**Comment by naacbin** [comment]
LGTM ! Nothing to add on my side

**Comment by emtuls** [comment]
Looks good! Thanks for documenting all of that.

**Comment by Ana06** [comment]
Closing this issue then! @mandiant/commando-vm do you have any commando VM specific testing setup? If so, it would be a good idea to open an issue to add some documentation to this new page when you have time. :wink:

**Comment by day1player** [comment]
LGTM!
