### ISSUE TITLE
arsenalimagemounter.vm 3.11.279 is missing a dependency

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#852]
### Details

Arsenal Image Mounter 3.11.279 requires .NET 8: https://arsenalrecon.com/products/arsenal-image-mounter/downloads .NET 8 is not required in the community package and our package is requiring .NET 6, which means the package is missing a needed dependency. Two options:
- Fix arsenalimagemounter.vm to version 3.11.278 fixing the arsenalimagemounter dependency and using the dotnet-6.vm as dependency so that there are no more automatic updates. This requires deleting version 3.11.279 from myget as we would be downgrading the version.
- Introduce a `dotnet-8.vm` similar to https://github.com/mandiant/VM-Packages/pull/812/files and use it as dependency in arsenalimagemounter.vm 2.11.279

@mandiant/commando-vm any preferences?

**Comment by naacbin** [comment]
Since only this package require dotnet-8, I would recommend to add `dotnet-8.0-desktopruntime` as dependency. Until other packages needs the same dependency.

**Comment by naacbin** [comment]
Close as #895 as been merged
