### ISSUE TITLE
Package proposal: x64dbg.vm

### ISSUE THREAD

**Issue by stevemk14ebr** [mandiant/VM-Packages#853]
### Package Name

x64dbg

### Tool Name

x64dbg

### Package type

ZIP_EXE

### Is the tool a console application?

false

### Tool's version number

2024-01-06_21-29

### Category

Debuggers

### Tool's authors

mrexodia

### Tool's description

An open-source user mode debugger for Windows. Optimized for reverse engineering and malware analysis.

### Download URL

https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2024-01-06_21-29.zip

### Download SHA256 Hash

467e41d68e489aad288cb0d868ea37ceb9dcda3757d9badc6314964d847e26b4

### Why is this tool a good addition?

We currently install x64dbg from chocolatey. That version is nearly 3 years old at this point and is clearly not maintained. MrExodia does release via github release very frequently, so issue is to suggest switching to that.

**Comment by stevemk14ebr** [comment]
I have also contacted the chocolately admins to ask for a package update there, but honestly, us using the github release would still be much better.

**Comment by Ana06** [comment]
Thanks for the suggestion @stevemk14ebr!

@vm-packages the date seems to be used as the version:
![Screenshot 2024-01-23 at 13 39 11](https://github.com/mandiant/VM-Packages/assets/16052290/a5061aff-e9dd-4a1f-8215-5d5989ac05f8)

should we use `2024.01.06` as version for the package? This is consistent with the current package.

If we want to update this package automatically, we would need to modify the update script to consider versions with `-`, as at the moment only `.` are allowed: https://github.com/mandiant/VM-Packages/blob/main/scripts/utils/update_package.py#L59

**Comment by stevemk14ebr** [comment]
A dotted date makes sense as the version

**Comment by Ana06** [comment]
@stevemk14ebr we are not using the chocolatey package, but this url: `https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_$snapshotDate.zip`

So modifying `$snapshotDate` in `packages/x64dbg.vm/tools/chocolateyinstall.ps1` would also update the tool (and it is very easy to change it):
https://github.com/mandiant/VM-Packages/blob/79c35a70707ea79f01559eceb76eac000e029bd4/packages/x64dbg.vm/tools/chocolateyinstall.ps1#L11 

The only advantage to change to GitHub releases would to benefit from automatic updates (which as said requires changes in the current script). @stevemk14ebr do you know if the maintainer is planing to continue using GH releases? I see only one recent release in GH, but some more in sourceforge.

**Comment by stevemk14ebr** [comment]
I just asked, SF is the primary release channel (I was wrong about GH earlier). So we should bump to the latest hosted on SF
