### ISSUE TITLE
Add 7zip (current version)

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#87]
Currently, only 7zip 15.05 (with NSIS support) gets installed.
- [ ] add the current version via metapackage
- [ ] change existing package to indicate it's 15.05

**Comment by MalwareMechanic** [comment]
@mr-tz do we need the current version?

If both are installed how would the user know which one to use and when? The right-click context menu may be dependent upon which ever gets installed last.

**Comment by mr-tz** [comment]
Well, maybe? A newer version will have less bugs and more functionality/supported files (except NSIS lol).

**Comment by MalwareMechanic** [comment]
Ight, I vote we rename it to reflect the specific version. Then if users want an up to date version of 7zip, we'll wait for the community to ask for it. Thoughts?

**Comment by mr-tz** [comment]
Yes, great plan!
