### ISSUE TITLE
Exiftool.vm not installing when running script

### ISSUE THREAD

**Issue by Baker-101** [mandiant/VM-Packages#872]
### What's the problem?

When I run the script for FlareVM and following the instructions, I get the error that "exiftool (error 404)" when it tries to pull and install exiftool-12.73.zip from https://exiftool.org/

### Steps to Reproduce

1. Run script as normal
2. Wait for it to reach the step to install exiftool

### Environment

- Virtualization software: Virtualbox
- VM OS Version: 10.0.19045
- VM Powershell version: 5.1.19041.3803
- VM Chocolatey Version: Unable to check as installation cannot be complete
- VM Boxstarter version: Unable to check as installation cannot be completed
- Output of VM-Get-Host-Info: Unable to check as installation cannot be completed

### Additional Information

I believe the error lies in that the exiftool on the site is ExifTool-12.74.zip, not ExifTool-12.73.zip
![output error](https://github.com/mandiant/VM-Packages/assets/90106544/55007544-6776-4515-8012-0e6c9fa1f35d)

### Detected by test suite

Yes

**Comment by rethinksec** [comment]
Can we use the production version (As of today it is 12.75) instead? In that case the production version is always available as compared to non-production version (In this case, 12.73 or 12.74). I can create a PR if that is a better approach.

**Comment by mr-tz** [comment]
Problem seems to be that the download links disappear. 12.74 and 12.75 seem available right now. Our package relies on the https://community.chocolatey.org/packages/exiftool package which has the hard-coded URL for 12.74 currently, but the dependency is not updated yet (it's in https://github.com/mandiant/VM-Packages/pull/864 though).

**Comment by Baker-101** [comment]
In addition, a few more packages that failed to install was peanatomist.vm, minidump.vm, resorcehacker.portable, resourcehacker.vm, and metasplot.vm

**Comment by Ana06** [comment]
exiftool.vm has been fixed in https://github.com/mandiant/VM-Packages/pull/864
