### ISSUE TITLE
Remove cmder from the Tools directory

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#880]
### Details

cmder is nice to have but is not an analysis tool. It is similar 7z, googlechrome and microsoft-windows-terminal, so I suggest we remove it the shortcut from the Tool directory.

**Comment by emtuls** [comment]
I agree that it is not an analysis tool and falls into a similar category as the rest.

Typically, we put these tools into the `RAW_TOOLS_DIR`, which is fine, but I think that there is a decent alternative to consider, particularly for things like `cmder` which I originally found through using `FLARE-VM` and have come to like it, but may never have found it if it was stashed away from where other tools are usually located.

I propose making a new category for these types of tools called `Productivity Tools` (or similar anyone else has a suggestion) as they are useful tools to consider.
