### ISSUE TITLE
PE-Sieve Tool Category Change

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#881]
### Details

Currently, this tool sits in the category of `Utilities`. This is an okay placement, but I feel it may be better suited in the `PE` category, but it depends how we intend to use "PE" as a category.

One thing to note, `hollows_hunter` is a similar tool and it current resides in the `PE` category: https://github.com/mandiant/VM-Packages/blob/main/packages/hollowshunter.vm/tools/chocolateyinstall.ps1#L5

**Comment by mr-tz** [comment]
hm, I don't feel too strongly either way, it's not a PE (viewer) tool that I first think of, but I can see it being moved (especially, if there's already other similar/related tools in PE

**Comment by emtuls** [comment]
I agree. I typically associate PE with things related to specific PE file analysis things, so it doesn't feel right to me to have `hollows_hunter` in there, but if our goal is things associated with anything PE related, then I guess `PE-Sieve` should go in there as well.

I put my thoughts and recommendations also in this issue: https://github.com/mandiant/VM-Packages/issues/883

**Comment by Ana06** [comment]
From FLARE-VM we had seen `PE` as the category for PE viewers so far. We could create another extra category for memory dumps (or something similar) where PE-Sieve fits better. 🤔
