### ISSUE TITLE
Change `burpsuite.vm` Category to `Web Applications` or `Networking`

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#885]
### Details

Currently, burpsuite is in the `Utilities` category. I think it is better suited inside of `Web Applications` or `Networking`.

`Web Applications` currently has no tools associated with it, so I'm unsure if we should add it to that category, but it does make sense.

**Comment by day1player** [comment]
Web Applications is probably the only category I would be hesitant to remove but I will defer that convo to the other issue.. If we decide to keep web apps, that's where Burp should live
