### ISSUE TITLE
OpenJDK Path Uses Hardcoded Version Causing Auto Update To Fail

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#889]
### What's the problem?

The OpenJDK package uses a hardcoded version number to locate `javaw.exe` as seen here: https://github.com/mandiant/VM-Packages/blob/main/packages/openjdk.vm/tools/chocolateyinstall.ps1#L6

This is causing the auto updater to fail: https://github.com/mandiant/VM-Packages/pull/864

### Steps to Reproduce

View logs for PR 864 here: https://github.com/mandiant/VM-Packages/actions/runs/7733944163/job/21094276941?pr=864

### Environment

Env Independent

### Detected by test suite

No

**Comment by Ana06** [comment]
As mentioned in https://github.com/mandiant/VM-Packages/pull/890#discussion_r1475661066 (so that it is documented in the issue as well):
> I think we shouldn't update core tools (like OpenJDK, Python, etc.) automatically. The purposes of these metapackages is that only one version of the tool is required for all packages to ensure there are not dependency conflicts when installing several packages. In the other metapackages like this, we are fixing the dependency to prevent updates. For example in python3.vm:
`<dependency id="python3" version="[3.10.0, 3.11.0)" />`

**Comment by Ana06** [comment]
But there may still be a bug here. Our bot should not send broken updates, which seems to be happening. Any idea where the issue could be @emtuls?

**Comment by Ana06** [comment]
I think the issue may be related to updating apktool.vm together with openjdk.vm (a dependency of apktool.vm) and only checking that apktool.vm succeeds to install. I having analysed the issue in detail though.

**Comment by emtuls** [comment]
Yea, when I looked at it, it seemed to be an issue with `openjdk` failing to update which was a dependency for `apktool`. Didn't think that when updating a dependency in the same run may cause an issue like that, but it's good to note.

Fixing the `openjdk` version in https://github.com/mandiant/VM-Packages/pull/890 should fix this. :)
