### ISSUE TITLE
Do not allow bot to overwrite someone else changes

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#896]
### Details

We should add a `--force-with-lease` to our bot to avoid that it overwrites someone else changes when updating packages like in https://github.com/mandiant/VM-Packages/pull/864#issuecomment-1936285583

**Comment by mr-tz** [comment]
or we can create unique branches including the date here:

https://github.com/mandiant/VM-Packages/blob/201a848bdbcff263368a702a79e313a5e32ba70c/.github/workflows/update_package.yml#L64

**Comment by Ana06** [comment]
@mr-tz 
> or we can create unique branches including the date here:

This will create several updates PRs, which I don't think it is desirable. The bot at the moment overwrites its own changes adding more updates and removing broken owns if the PR is not merged within a week or if triggered manually. I think this is a nice feature we want to keep. If we modified manually the PR, it is because there is an issue, so we don't want the bot to send another broken PR.

**Comment by Ana06** [comment]
I have open an issue at https://github.com/peter-evans/create-pull-request/issues/2766

**Comment by Ana06** [comment]
The bot is already using `--force-with-lease` (see https://github.com/peter-evans/create-pull-request/issues/2766). I think we should close this issue, as we would have to lose some nice feature to ensure the bot does not change the PR. I think it is not worthwhile, as this has only happened once and we can ensure we merge quick when manually modifying bot PR or push the changes to a new PR.

**Comment by Ana06** [comment]
We could at least improve the comment in the PR to help people reviewing the changes that may not be familiar with the automation.
