### ISSUE TITLE
Package proposal: extreme_dumper.vm

### ISSUE THREAD

**Issue by av-gantimurov** [mandiant/VM-Packages#901]
### Package Name

extreme_dumper

### Tool Name

ExtremeDumper

### Package type

ZIP_EXE

### Is the tool a console application?

false

### Tool's version number

4.0.0.1

### Category

dotNet

### Tool's authors

wwh1004

### Tool's description

.NET Assembly Dumper from memory of processes.

### Download URL

https://github.com/wwh1004/ExtremeDumper/releases/latest/download/ExtremeDumper.zip

### Download SHA256 Hash

fbffedf2a9420be03538f04bd80a69e35503f8d8395da76a9ac2518a65e1facc

### Why is this tool a good addition?

More powerfull version than MegaDumper (https://github.com/CodeCracker-Tools/MegaDumper)

I use extreme dumper for dump malicious .NET modules already unpacked in memory by previous stages of execution.

## Features

1. List all processes and highlight .NET processes
2. List all modules in a process and highlight .NET modules
3. Walk memory pages and dump all valid .NET assemblies
4. Dump specified module in modules view
5. Inject .NET assembly into any process
6. Enhanced anti-dump bypass mode
7. .NET assembly loader hook
8. Anti title keyword detection
9. Portable and only one executable file

**Comment by Ana06** [comment]
@av-gantimurov thanks for the proposal! the zip appears to include a x86 version, do we need to install both?

**Comment by av-gantimurov** [comment]
> @av-gantimurov thanks for the proposal! the zip appears to include a x86 version, do we need to install both?

no, it's not necessary. X64 ExtremeDumper can dump x86 processes too.
x86 only for compatibilty with Windows x86.

**Comment by Ana06** [comment]
@mandiant/flare-vm is any of you familiar with this tool? opinions on adding it to the default configuration?

**Comment by Ana06** [comment]
extreme_dumper.vm added! 🎉 @av-gantimurov thanks for the proposal and filling the issue accurately. 😉
