### ISSUE TITLE
[arsenalimagemounter.vm] Install missing drivers

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#910]
### Details

From https://github.com/mandiant/VM-Packages/pull/895:

I get the following message when opening Arsenal Image Mounter:
![Screenshot 2024-02-14 at 11 10 48](https://github.com/mandiant/VM-Packages/assets/16052290/db231da9-67b2-4e7c-a683-ebd57b098717)

Options to install the missing driver (proposed by @naacbin):
- [DriverFiles.zip](https://github.com/ArsenalRecon/Arsenal-Image-Mounter/blob/master/DriverSetup/DriverFiles.zip) file contains a folder DriverFiles\Win10\x64 with 6 drivers 5 have to be installed.
- Launch the application and click yes with autohotkey.

**Comment by naacbin** [comment]
Close as #963 as been merged
