### ISSUE TITLE
Package proposal: RegCool.vm

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#923]
### Package Name

regcool

### Tool Name

RegCool

### Package type

ZIP_EXE

### Is the tool a console application?

false

### Tool's version number

1.361

### Category

Utilities

### Tool's authors

Kurt Zimmermann

### Tool's description

In addition to all the features that you can find in RegEdit and RegEdt32, RegCool adds many powerful features that allow you to work faster and more efficiently with registry related tasks

### Download URL

https://kurtzimmermann.com/files/RegCoolX64.zip

### Download SHA256 Hash

9b15369b688a5cabcf86f6ecc725d99678a60bf0c370bfd1b0d9cccf2eee9003

### Why is this tool a good addition?

This tool greatly improves RegEdit and gives it many more features that make registry analysis more bearable.

**Comment by emtuls** [comment]
They are a little bit similar but they each have different features that are both kind of nice to have. But I can pick one vs the other if that's preferred. 🙂

**Comment by Ana06** [comment]
@emtuls we can add both to VM-Packages, but I would prefer that you pick only one to add to the default FLARE-VM config. :wink:
