### ISSUE TITLE
add frida and frida-tools into modules.xml

### ISSUE THREAD

**Issue by binjo** [mandiant/VM-Packages#960]
### Details

The [frida](https://frida.re/) is a dynamic instrumentation toolkit for developers, reverse-engineers, and security researchers. It's handy to do quick triage for malware analysis too. It can be installed through:
```
pip install frida
pip install frida-tools
```

Does add into the [libraryis.python3.vm](https://github.com/mandiant/VM-Packages/blob/main/packages/libraries.python3.vm/tools/modules.xml) sufficient for inclusion?

https://github.com/frida/frida

**Comment by Ana06** [comment]
Yes, libraries.python3.vm is where we install common Python libraries. Thanks for the issue and the PR! :+1:
