### ISSUE TITLE
Use CyberChef icon instead of Chrome icon for CyberChef?

### ISSUE THREAD

**Issue by emtuls** [mandiant/VM-Packages#966]
### Details

Currently we use the Chrome icon for opening Cyberchef which works well and is dual purpose since it also acts as a chrome shortcut, but is there a necessity for this case?

People in the community may assume that it is only Chrome Browser shortcut and not realize that it is also a CyberChef shortcut and due to this being a malware analysis environment, it might make sense to use the CyberChef icon versus a Chrome one. The functionality wouldn't change of course, just the icon.

Not sure if this is something we should consider or not and I definitely don't have strong feelings one way or another. I do like the CyberChef icon due to it being more explicit about what it is primarily for, but I also know that a Chrome shortcut may make a lot of sense.

Opening for discussion and thoughts on possible preference. :)

**Comment by Ana06** [comment]
I would prefer the CyberChef icon in the Tools folder, but I am not sure if it may be confusing in the taskbar. :thinking:

**Comment by emtuls** [comment]
Hmmm, if our goal is to have `CyberChef` pinned to the taskbar, it might be more clear to show an official `CyberChef` icon rather than Google Chrome, which people might assume may just be a Google Chrome browser shortcut.

From the perspective of someone who might not be too familiar with FlareVM, this is what I could imagine:
If someone wants to use Chrome, I would imagine they would likely click the current icon in the taskbar, which theoretically does work, but is not our intention for it. 
And if someone wants to use CyberChef, they may not realize that the shortcut is for CyberChef (since it just looks like a Google Chrome shortcut) and they would likely search for "CyberChef" and find it in the Tools folder rather than use the shortcut. That is, until they maybe one day realize that the shortcut in the taskbar leads them to opening CyberChef directly.

**Comment by stevemk14ebr** [comment]
I would love a cyberchef icon pinned to the dash. I do this myself with a little bash script and then change the icon on that to cyberchef

**Comment by Ana06** [comment]
@stevemk14ebr we are using [CustomStartLayout.xml](https://github.com/mandiant/flare-vm/blob/main/CustomStartLayout.xml) to ping icons to the taskbar, so the implementation itself is not difficult. :wink: It seems we agree that we prefer having the CyberChef icon in the Tools folder and the taskbar. I think this could be implemented together with 
https://github.com/mandiant/VM-Packages/issues/1021 and https://github.com/mandiant/VM-Packages/issues/822 nicely: cyberchef shortcut is an .html with the cyberchef icon that opens with the default browser and we get chrome as default browser in the chrome package. @emtuls would you like to work on these issues? :smile:
