### ISSUE TITLE
Metapackage proposal: neo4j-community.vm

### ISSUE THREAD

**Issue by Menn1s** [mandiant/VM-Packages#975]
### Package Name

neo4j-community

### Tool Name

neo4j

### Package type

METAPACKAGE

### Tool's version number

3.5.1.2024.04.03

### Category

Utilities

### Tool's authors

neo4j

### Tool's description

A major graph database that is used as the DBMS backend for BloodHound.

### Dependency

neo4j-community

### Shim path

%PROGRAMDATA%\chocolatey\bin\neo4j.exe

### Why is this tool a good addition?

This tool is needed for the use of BloodHound, commonly used for Active Directory analysis.

**Comment by emtuls** [comment]
Hi @Menn1s.

I took a look and it doesn't explicitly say it in that log view and the error is VERY misleading, but it looks to be an issue with the version number which is what the log is also showing.

![image](https://github.com/mandiant/VM-Packages/assets/35854880/97d472b5-a74d-4dbe-a635-49aecac825f7)

You put the version number as `3.5.1.2024.04.03`, which doesn't conform to the Versioning standard in the wiki noted here: https://github.com/mandiant/VM-Packages/wiki/Package-Structure#version

It should be `3.5.1.20240403`. 🙂

Also, if the package is not needed. Feel free to close the issue when you are sure that everything is good to go!

**Comment by Ana06** [comment]
As @emtuls said, it is because the invalid version format (you can only use 4th segments, see [documentation in the wiki](https://github.com/mandiant/VM-Packages/wiki/Package-Structure#version)). If you edit the first comment of this issue to correct the version and add the label again, it should work. :wink:

**Comment by Ana06** [comment]
@Menn1s 

>  turns out we don't need this package because of changes to bloodhound and neo4j

should we then close this issue? :smiley:

**Comment by Menn1s** [comment]
Issue is good to close, thanks Ana!
