### ISSUE TITLE
peview failed to install

### ISSUE THREAD

**Issue by Muitinkinyakkin** [mandiant/VM-Packages#976]
### What's the problem?

I have ran the installation, and Flare is running with no issues. However, I am missing **_peview_**. Has the naming changed may be? If not, how can I install any missing single packages?

### Steps to Reproduce

N/A

### Environment

Virtualization software: VMWare
VM OS version: 10.0.19045
VM PowerShell version: 5.1.19041.4170 
VM Chocolatey version: 2.2.2
VM Boxstarter version: Boxstarter 3.0.3 
Output of VM-Get-Host-Info: 

Version : 10.0.19045                                                                                    
BuildNumber: 19045                                                                                         
OSArchitecture: 64-bit                                                                                       
 ServicePackMajorVersion : 0                                                                                             
Caption: Microsoft Windows 10 Home 

### Detected by test suite

No

**Comment by emtuls** [comment]
Hello @Muitinkinyakkin! Thank you for your submission.

I don't believe `peview` is a tool that we install in `flare-vm` at the moment. The tool is a bit outdated and there have been many (unofficial) successors. I would recommend trying `CFF Explorer` which should be installed by default. 

If not, you can try to run `choco install 'explorersuite.vm'` and it should install it (along with some other tools), inside the `PE` category in the `Tools` directory on the desktop.

**Comment by Muitinkinyakkin** [comment]
Solved! CFF Explorer is already in.
Ty!
