### ISSUE TITLE
rename fiddlerclassic.vm to fiddler.vm

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#985]
### Details

`fiddlerclassic.vm` version is not being currently updated correctly by our bot because it does not follow [our documentation](https://github.com/mandiant/VM-Packages/wiki/Package-Structure#metapackages). We should rename the package to `fiddler.vm` so that the dependency and the package have the same name and our CI updates its version as a metapackage. Any objection in doing this change @mandiant/commando-vm? 

Related: https://github.com/mandiant/VM-Packages/issues/972

**Comment by geo-lit** [comment]
No objection @Ana06
