### ISSUE TITLE
Split `pdbresym.vm` in `pdbresym.vm` and `pdbs.pdbresym.vm`

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#991]
### Details

As per @stevemk14ebr feedback in https://github.com/mandiant/VM-Packages/pull/986#issuecomment-2051987881, I think we should split the downloading of the symbol in a separate package, something like `pdbresym.vm` (just the tool) and `pdbs.pdbresym.vm` (which requires the tool and download the symbols).

@mandiant/flare-vm opinions on the naming? Should we add the new `pdbresym.vm` to the default flare-vm config?

**Comment by stevemk14ebr** [comment]
I like this idea, and I agree with Elliot this is the best way for now (per linked issue)

**Comment by stevemk14ebr** [comment]
Thanks Ana!
