### ISSUE TITLE
ida.plugin.diaphora.vm: Install it as an IDA plugin

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#994]
### Details

ida.diaphora.vm is just copying the diaphora script to the Utilities folder. From discussions I had with users, I get the impression that diaphora is not being noticed and that it would be much useful if we would install it as a plugin as we do in ida.plugin.capa.vm and rename it as ida.plugin.diaphora.vm.

**Comment by emtuls** [comment]
I think it's a great plugin! Would be nice to have it installed properly if possible. Thank you for looking into it!

**Comment by Ana06** [comment]
I have explored writing a plugin file to wrap the script. The issue is to run the diaphora code with the current project structure, as it is not a Python module. Making the project a Python module would only imply changing the imports in diaphora to be prepended by `diaphora.`. After that, coping the diaphora plugin file and the diaphora Python module folder (similar to how we do with the [`flare` module in ida.plugin.flare.vm](https://github.com/mandiant/VM-Packages/blob/main/packages/ida.plugin.flare.vm/tools/chocolateyinstall.ps1#L31) would install diaphora as a plugin. So taking this into account, I think we should ask upstream if they would be up to supporting installing diaphora as a plugin and see if we can help.

**Comment by Ana06** [comment]
diaphora has now plugin support: https://github.com/joxeankoret/diaphora/issues/301 :tada: Waiting for the release to make the change in VM-Packages :wink:
